const test=require('node:test'),assert=require('node:assert/strict'),E=require('./predator-engine.js');
const empty=(terrain=null)=>E.create(42,{plants:0,herbivores:0,carnivores:0,plantSpawnRate:0,herbivoreDeathProb:0,carnivoreDeathProb:0},terrain,true);
test('same seed, settings and map reproduce every decision and energy change',()=>{const run=()=>{const s=E.create(91);E.preset(s,'meadow');for(let i=0;i<140;i++)E.step(s);return s;};assert.deepEqual(run(),run());});
test('basic mode preserves unlimited nearest-food detection; spatial brush reduces discovery distance',()=>{const s=empty(),a={kind:'carnivore',x:20,y:20},b={x:120,y:20};assert.equal(E.canDetect(s,a,b),true);s.terrain[E.index(b.x,b.y)]=1;assert.equal(E.canDetect(s,a,b),false);s.spatial=false;assert.equal(E.canDetect(s,a,{x:799,y:799}),true);});
test('rock blocks both sight and movement; animals take an open route and remain outside rock',()=>{const s=empty();s.terrain[1]=3;assert.equal(E.visible(s,{x:20,y:20},{x:100,y:20}),false);assert.ok(E.path(s,{x:20,y:20},{x:100,y:20}).length>3);const id=E.add(s,'herbivore',20,20);E.plant(s,100,20);s.settings.speed=3;for(let i=0;i<100;i++){E.step(s);assert.equal(E.summary(s).rockFree,true);}assert.ok(s.herbivores.find(a=>a.id===id));});
test('feeding patches change real plant regeneration sites without changing the spawn probability',()=>{const s=empty();s.settings.plantSpawnRate=1;s.terrain[210]=2;for(let i=0;i<30;i++)E.step(s);assert.ok(s.plants.length>0);assert.ok(s.plants.every(p=>E.index(p.x,p.y)===210));});
test('painting protects occupied cells and basic preset removes spatial restrictions',()=>{const s=empty();E.add(s,'herbivore',20,20);assert.equal(E.paint(s,0,3),false);assert.equal(s.terrain[0],0);assert.equal(E.paint(s,100,3),true);E.preset(s,'basic');assert.equal(s.spatial,false);assert.ok(s.terrain.every(v=>v===0));});
test('actual energy and observed reason follow a real feeding event',()=>{const s=empty();const id=E.add(s,'herbivore',20,20);E.plant(s,20,20);E.step(s);const a=s.herbivores.find(a=>a.id===id);assert.equal(a.energy,119.9);assert.match(a.reason,/섭취/);assert.ok(Math.abs(a.lastDelta-19.9)<1e-9);});

test('restoring old rock after unrestricted movement is rejected without changing the current map',()=>{const s=E.create(73,{plantSpawnRate:0,herbivoreDeathProb:0,carnivoreDeathProb:0});E.preset(s,'passage');const snapshot={terrain:[...s.terrain],spatial:s.spatial};E.preset(s,'basic');for(let i=0;i<25;i++)E.step(s);assert.equal(E.restoreTerrain(s,snapshot),false);assert.ok(s.terrain.every(v=>v===0));assert.equal(E.summary(s).rockFree,true);});
test('cached shortest paths invalidate for paint, preset, restore and direct terrain edits',()=>{const s=empty(),a={x:20,y:20},b={x:100,y:20};assert.deepEqual(E.path(s,a,b),[0,1,2]);assert.ok(E.paint(s,1,3));const detour=E.path(s,a,b);assert.deepEqual(detour,[0,20,21,22,2]);const snapshot={terrain:[...s.terrain],spatial:true};E.preset(s,'open');assert.deepEqual(E.path(s,a,b),[0,1,2]);assert.ok(E.restoreTerrain(s,snapshot));assert.deepEqual(E.path(s,a,b),detour);s.terrain[1]=0;assert.deepEqual(E.path(s,a,b),[0,1,2]);s.terrain[0]=3;assert.equal(E.path(s,a,b),null);});
test('cached route fields preserve shortest lengths, endpoints and four-neighbor movement',()=>{const s=empty();E.preset(s,'passage');const expected=(start)=>{const d=Array(400).fill(Infinity),q=[start];d[start]=0;for(const i of q){for(const j of[i-1,i+1,i-20,i+20]){if(j<0||j>=400||Math.abs(i%20-j%20)+Math.abs(Math.floor(i/20)-Math.floor(j/20))!==1||s.terrain[j]===3||d[j]<Infinity)continue;d[j]=d[i]+1;q.push(j);}}return d;};for(const start of[0,19,180,210,399]){const d=expected(start);for(let end=0;end<400;end+=7){const route=E.path(s,E.center(start),E.center(end));if(s.terrain[end]===3||!Number.isFinite(d[end]))assert.equal(route,null);else{assert.equal(route[0],start);assert.equal(route.at(-1),end);assert.equal(route.length,d[end]+1);assert.ok(route.every(i=>s.terrain[i]!==3));}}}});
const loadApp=require('../reef_market/app-test-harness.cjs');
test('real UI expires old map undo after 25 unrestricted steps and preserves immediate undo',()=>{const app=loadApp('predator_prey_simulator','PredatorEngine','?seed=73&plantSpawn=0&herbivoreDeath=0&carnivoreDeath=0');app.select('terrain-preset','passage');const old=app.state().terrain;app.select('terrain-preset','basic');app.click('undo-terrain');assert.deepEqual(app.state().terrain,old);app.select('terrain-preset','basic');app.context.advanceTime(25*1000/30);assert.equal(app.state().tick,25);assert.equal(app.element('undo-terrain').disabled,true);app.forceClick('undo-terrain');assert.equal(app.state().rockFree,true);assert.ok(app.state().terrain.every(v=>v===0));});
test('start, keyboard start, single step and either animal addition expire predator undo',()=>{for(const action of[app=>app.click('start-btn'),app=>app.key(' ','Space'),app=>app.click('step-btn'),app=>app.click('add-herbivore-btn'),app=>app.click('add-carnivore-btn')]){const app=loadApp('predator_prey_simulator','PredatorEngine');app.select('terrain-preset','passage');assert.equal(app.element('undo-terrain').disabled,false);action(app);assert.equal(app.element('undo-terrain').disabled,true);}});
