(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.PredatorEngine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  const SIZE=800,GRID=20,CELL=40,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const DEFAULTS={plants:50,herbivores:30,carnivores:2,speed:1,plantSpawnRate:.1,herbivoreBirthProb:.5,carnivoreBirthProb:.5,herbivoreDeathProb:.005,carnivoreDeathProb:.001};
  function random(s){s.rng=(s.rng*9301+49297)%233280;return s.rng/233280;}
  const index=(x,y)=>clamp(Math.floor(y/CELL),0,GRID-1)*GRID+clamp(Math.floor(x/CELL),0,GRID-1);
  const center=i=>({x:(i%GRID+.5)*CELL,y:(Math.floor(i/GRID)+.5)*CELL});
  const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
  const adjacency=Array.from({length:400},(_,i)=>{const x=i%GRID,y=Math.floor(i/GRID);return[[x-1,y],[x+1,y],[x,y-1],[x,y+1]].filter(([a,b])=>a>=0&&a<GRID&&b>=0&&b<GRID).map(([a,b])=>b*GRID+a);});
  const routeCaches=new WeakMap();
  // The graph depends only on terrain. Exact fingerprints also detect direct edits in tests/imports.
  function routeCache(s){const fingerprint=s.terrain.join(',');let cache=routeCaches.get(s);if(!cache||cache.fingerprint!==fingerprint){cache={fingerprint,fields:new Map()};routeCaches.set(s,cache);}return cache;}
  function neighbors(s,i){return adjacency[i].filter(j=>s.terrain[j]!==3);}
  function routeField(s,start,cache){let prev=cache.fields.get(start);if(prev)return prev;prev=new Int16Array(400).fill(-1);if(s.terrain[start]!==3){const queue=new Int16Array(400);queue[0]=start;prev[start]=start;let size=1;for(let at=0;at<size;at++)for(const j of adjacency[queue[at]])if(s.terrain[j]!==3&&prev[j]<0){prev[j]=queue[at];queue[size++]=j;}}cache.fields.set(start,prev);return prev;}
  function path(s,a,b,cache=routeCache(s)){const start=index(a.x,a.y),end=index(b.x,b.y),prev=routeField(s,start,cache);if(prev[end]<0)return null;const out=[end];while(out[out.length-1]!==start)out.push(prev[out[out.length-1]]);out.reverse();return out;}
  function visible(s,a,b){if(!s.spatial)return true;const n=Math.max(1,Math.ceil(distance(a,b)/8));for(let i=0;i<=n;i++)if(s.terrain[index(a.x+(b.x-a.x)*i/n,a.y+(b.y-a.y)*i/n)]===3)return false;return true;}
  function detectionRange(s,observer,target){if(!s.spatial)return Infinity;const base=observer.kind==='carnivore'?180:220;return base*(observer.kind==='carnivore'&&s.terrain[index(target.x,target.y)]===1?.38:1);}
  function canDetect(s,a,b){return distance(a,b)<=detectionRange(s,a,b)&&visible(s,a,b);}
  function plant(s,x,y){x=clamp(x,0,799.99);y=clamp(y,0,799.99);if(s.spatial&&s.terrain[index(x,y)]===3)return false;if(s.plants.some(p=>Math.hypot(p.x-x,p.y-y)<12))return false;s.plants.push({id:s.nextId++,x,y});return true;}
  function creature(s,kind,x,y){return{id:s.nextId++,kind,x,y,energy:100,eaten:0,slowTimer:0,reason:'아직 움직이지 않았습니다.',target:null,lastDelta:0,trail:[],route:[],wander:null};}
  function freePosition(s){for(let i=0;i<1000;i++){const p={x:random(s)*SIZE,y:random(s)*SIZE};if(!s.spatial||s.terrain[index(p.x,p.y)]!==3)return p;}return center(s.terrain.findIndex(v=>v!==3));}
  function create(seed=73,settings={},terrain=null,spatial=false){const s={seed:Math.abs(Math.trunc(seed))%233280,rng:Math.abs(Math.trunc(seed))%233280,settings:{...DEFAULTS,...settings},spatial,terrain:terrain?[...terrain]:Array(400).fill(0),tick:0,nextId:1,plants:[],herbivores:[],carnivores:[],eggs:[],history:[],deaths:[],lastEvent:'같은 시드의 생태계를 준비했습니다.'};for(let i=0;s.plants.length<s.settings.plants&&i<s.settings.plants*200;i++){const p=freePosition(s);plant(s,p.x,p.y);}for(const[k,n]of[['herbivore',s.settings.herbivores],['carnivore',s.settings.carnivores]])for(let i=0;i<n;i++){const p=freePosition(s);s[k==='herbivore'?'herbivores':'carnivores'].push(creature(s,k,p.x,p.y));}return s;}
  function move(s,a,target,speed,cache,knownRoute){let p=target;a.route=[];if(s.spatial){const route=knownRoute||path(s,a,target,cache);if(!route)return false;a.route=route.map(center);if(route.length>1)p=center(route[1]);}const d=distance(a,p);if(d){const n=Math.min(speed,d);a.x=clamp(a.x+(p.x-a.x)/d*n,0,799.99);a.y=clamp(a.y+(p.y-a.y)/d*n,0,799.99);}return true;}
  function findTarget(s,a,candidates,cache){let target=null,best=Infinity;const field=s.spatial?routeField(s,index(a.x,a.y),cache):null;for(const b of candidates){const bound=Math.min(best,detectionRange(s,a,b));if(Math.abs(a.x-b.x)>bound||Math.abs(a.y-b.y)>bound)continue;const d=distance(a,b);if(d>=best||d>detectionRange(s,a,b)||!visible(s,a,b)||(field&&field[index(b.x,b.y)]<0))continue;target=b;best=d;}return{target,route:target&&s.spatial?path(s,a,target,cache):null};}
  function wander(s,a,speed,cache){if(!a.wander||distance(a,a.wander)<8||s.tick%80===0){const reachable=neighbors(s,index(a.x,a.y));if(!reachable.length){a.reason='바위에 둘러싸여 이동할 수 없음';return;}a.wander=center(reachable[Math.floor(random(s)*reachable.length)]);}move(s,a,a.wander,speed*.65,cache);}
  function died(s,a,why){a.energy=0;s.deaths.push({...a,reason:why,tick:s.tick});if(s.deaths.length>100)s.deaths.shift();}
  function step(s){s.tick++;const v=s.settings,cache=s.spatial?routeCache(s):null;if(random(s)<v.plantSpawnRate){const sites=s.spatial?s.terrain.map((n,i)=>n===2?i:-1).filter(i=>i>=0):[];let p;if(sites.length){const i=sites[Math.floor(random(s)*sites.length)];p={x:(i%GRID+random(s))*CELL,y:(Math.floor(i/GRID)+random(s))*CELL};}else p=freePosition(s);plant(s,p.x,p.y);}
    for(const a of [...s.herbivores]){const before=a.energy;a.target=null;if(random(s)<v.herbivoreDeathProb){died(s,a,'자연사 확률에 해당');continue;}a.energy-=.1;if(a.energy<=0){died(s,a,'먹이를 얻지 못해 에너지 고갈');continue;}const threat=s.spatial?s.carnivores.filter(c=>c.energy>0&&distance(a,c)<110&&visible(s,a,c)).sort((c,d)=>distance(a,c)-distance(a,d))[0]:null;
      if(threat){const choices=neighbors(s,index(a.x,a.y)).map(center).sort((p,q)=>distance(q,threat)-distance(p,threat));if(choices.length)move(s,a,choices[0],v.speed,cache);a.reason='보이는 포식자를 피해 멀어지는 이웃 칸으로 이동';a.target={id:threat.id,x:threat.x,y:threat.y,kind:'danger'};}
      else{const {target,route}=findTarget(s,a,s.plants,cache);if(target){move(s,a,target,v.speed,cache,route);a.target={...target,kind:'plant'};a.reason=s.spatial?'발견 가능한 먹이로 바위를 우회':'가장 가까운 식물로 이동';}else{a.reason=s.spatial?'시야 안에 도달 가능한 식물이 없어 탐색':'남은 식물이 없어 대기';if(s.spatial)wander(s,a,v.speed,cache);}}
      for(let i=s.plants.length-1;i>=0;i--)if(Math.abs(a.x-s.plants[i].x)<5&&Math.abs(a.y-s.plants[i].y)<5&&distance(a,s.plants[i])<5){s.plants.splice(i,1);a.energy+=20;a.reason='식물 섭취: 에너지 +20';}if(a.energy>180&&random(s)<v.herbivoreBirthProb){a.energy/=2;s.eggs.push({id:s.nextId++,x:a.x,y:a.y,timer:150});a.reason='에너지 180 초과: 절반을 나눠 알 생성';}a.lastDelta=a.energy-before;
    }s.herbivores=s.herbivores.filter(a=>a.energy>0);
    for(const a of [...s.carnivores]){const before=a.energy;a.target=null;if(random(s)<v.carnivoreDeathProb){died(s,a,'자연사 확률에 해당');continue;}a.energy-=.15;if(a.energy<=0){died(s,a,'사냥 없이 에너지 고갈');continue;}const {target,route}=findTarget(s,a,s.herbivores,cache),speed=(a.slowTimer>0?.4:1.5)*v.speed;if(target){move(s,a,target,speed,cache,route);a.target={id:target.id,x:target.x,y:target.y,kind:'prey'};a.reason=s.spatial?'시야에 보이는 먹이를 통행 가능한 길로 추격':'가장 가까운 초식동물을 추격';}else{a.reason=s.spatial?'발견 가능한 먹이 없음: 수풀·시야·바위 확인':'남은 초식동물 없음';if(s.spatial)wander(s,a,speed,cache);}for(let i=s.herbivores.length-1;i>=0;i--)if(Math.abs(a.x-s.herbivores[i].x)<6&&Math.abs(a.y-s.herbivores[i].y)<6&&distance(a,s.herbivores[i])<6){const h=s.herbivores.splice(i,1)[0];died(s,h,'포식자 '+a.id+'에게 잡힘');a.energy+=40;a.eaten++;a.slowTimer=120;a.reason='사냥 성공: 에너지 +40, 잠시 느려짐';}if(a.slowTimer>0)a.slowTimer--;if(a.energy>200&&random(s)<v.carnivoreBirthProb){a.energy/=2;let p={x:clamp(a.x+(random(s)*10-5),0,799.99),y:clamp(a.y+(random(s)*10-5),0,799.99)};if(s.spatial&&s.terrain[index(p.x,p.y)]===3)p={x:a.x,y:a.y};s.carnivores.push(creature(s,'carnivore',p.x,p.y));a.reason='에너지 200 초과: 절반을 나눠 새 개체 생성';}a.lastDelta=a.energy-before;
    }s.carnivores=s.carnivores.filter(a=>a.energy>0);for(const e of [...s.eggs])if(--e.timer<=0){s.eggs.splice(s.eggs.indexOf(e),1);s.herbivores.push(creature(s,'herbivore',e.x,e.y));}for(const a of [...s.herbivores,...s.carnivores])if(s.tick%5===0){a.trail.push({x:a.x,y:a.y});if(a.trail.length>14)a.trail.shift();}if(s.tick%10===0){s.history.push({tick:s.tick,plants:s.plants.length,herbivores:s.herbivores.length,carnivores:s.carnivores.length});if(s.history.length>180)s.history.shift();}return summary(s);
  }
  function paint(s,i,value){if(i<0||i>=400)return false;if(value===3&&[...s.plants,...s.herbivores,...s.carnivores,...s.eggs].some(a=>index(a.x,a.y)===i)){s.lastEvent='생물이나 알이 있는 칸에는 바위를 놓지 않습니다.';return false;}if(value===3&&s.terrain.filter(x=>x!==3).length<=2){s.lastEvent='열린 땅을 두 칸 이상 남겨 주세요.';return false;}s.terrain[i]=value;s.spatial=true;s.lastEvent=['땅으로 되돌렸습니다.','수풀: 이 안의 먹이를 발견하는 거리가 줄어듭니다.','먹이터: 식물 재생을 이 칸들로 모읍니다.','바위: 시야와 이동을 차단합니다.'][value];return true;}
  function preset(s,name){s.terrain.fill(0);s.spatial=name!=='basic';if(name==='meadow'){for(let y=4;y<8;y++)for(let x=3;x<7;x++)s.terrain[y*20+x]=2;for(let y=10;y<16;y++)for(let x=12;x<17;x++)s.terrain[y*20+x]=1;}if(name==='passage'){for(let y=0;y<20;y++)if(y!==9&&y!==10)s.terrain[y*20+10]=3;for(let y=3;y<7;y++)for(let x=3;x<6;x++)s.terrain[y*20+x]=2;for(let y=12;y<16;y++)for(let x=14;x<18;x++)s.terrain[y*20+x]=1;}if(name==='serpentine')for(const[x,gap]of[[5,17],[10,3],[15,17]])for(let y=0;y<20;y++)if(Math.abs(y-gap)>1)s.terrain[y*20+x]=3;if(name==='islands')for(let y=0;y<20;y++)for(let x=0;x<20;x++){const d=Math.min(...[[5,5,3],[14,6,3],[10,14,4]].map(([cx,cy,r])=>Math.hypot(x-cx,y-cy)/r));if(d<=1)s.terrain[y*20+x]=d<.42?2:1;if(Math.hypot(x-3,y-14)<2.2)s.terrain[y*20+x]=3;}for(const a of [...s.plants,...s.herbivores,...s.carnivores,...s.eggs])if(s.terrain[index(a.x,a.y)]===3)s.terrain[index(a.x,a.y)]=0;s.lastEvent=name==='basic'?'기존 무지형 모형으로 돌아왔습니다.':'지형 규칙을 켰습니다. 살아 있는 개체의 칸은 비워 둡니다.';}
  function restoreTerrain(s,snapshot){if(snapshot.spatial&&[...s.plants,...s.herbivores,...s.carnivores,...s.eggs].some(a=>snapshot.terrain[index(a.x,a.y)]===3)){s.lastEvent='현재 생물이나 알의 위치와 맞지 않아 이전 지도를 복원하지 않았습니다.';return false;}s.terrain=[...snapshot.terrain];s.spatial=snapshot.spatial;return true;}
  function add(s,kind,x,y){const p=x==null?freePosition(s):{x:clamp(x,0,799.99),y:clamp(y,0,799.99)};if(s.spatial&&s.terrain[index(p.x,p.y)]===3)return false;const a=creature(s,kind,p.x,p.y);s[kind==='herbivore'?'herbivores':'carnivores'].push(a);return a.id;}
  function summary(s){return{tick:s.tick,seed:s.seed,spatial:s.spatial,plants:s.plants.length,herbivores:s.herbivores.length,carnivores:s.carnivores.length,eggs:s.eggs.length,bounded:[...s.plants,...s.herbivores,...s.carnivores,...s.eggs].every(a=>a.x>=0&&a.x<800&&a.y>=0&&a.y<800),rockFree:[...s.herbivores,...s.carnivores].every(a=>s.terrain[index(a.x,a.y)]!==3)};}
  return{DEFAULTS,SIZE,GRID,CELL,create,step,random,index,center,path,visible,canDetect,detectionRange,paint,preset,restoreTerrain,add,plant,summary};
});
