(() => {
  'use strict';
  const E = window.InformationCascade, $ = id => document.getElementById(id), canvas = $('canvas'), ctx = canvas.getContext('2d'), stage = $('stage');
  const example = { truth: -1, signals: [1,1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1] };
  const modeNames = { choices:'선택만 공개', hints:'힌트도 공개', independent:'독립 결정' };
  const presets = { cascade: { mode:'choices', order:'original', brief:'당첨공은 A와 B 상자 중 하나에 있습니다. 각자 정확도 70%의 힌트 쪽지를 한 장씩 받습니다. 열두 사람 뒤에서 직접 상자를 고르고, 숨은 쪽지를 공개해 보세요.' }, evidence: { mode:'hints', order:'original', brief:'첫 실험과 같은 정답·같은 힌트입니다. 이번에는 앞사람이 본 힌트까지 공개합니다. 줄의 방향이 바뀌는 순간을 찾아보세요.' }, order: { mode:'choices', order:'reverse', brief:'첫 실험과 같은 사람들이 거꾸로 들어옵니다. 누구의 힌트도 바꾸지 않았는데, 긴 줄은 같은 쪽에 생길까요?' }, free: { mode:'choices', order:'original', brief:'당첨공은 A와 B 상자 중 같은 확률로 정하고, 각 힌트를 독립적으로 뽑습니다. 같은 시드에서 공개 방식과 순서만 바꿔 비교하세요.' } };
  let source, signals, mode='choices', order='original', quality=.7, seed=731, mission='cascade', events=[], index=0, logOdds=0, player=null, revealed=false, running=false, elapsed=0, comparison=null, previous=null, W=900,H=560,lastFrame=0, reasonIndex=-1, alternateHint=false, pointerStart=null, decisionTimes=[], revealTime=-10000;
  const ambientEnabled=()=>window.WebSimAmbient?.enabled===true, appearanceTime=()=>window.WebSimAmbient?.now?.()||0;
  const letter = v => v===1?'A':'B', color = v => v===1?'#21654f':'#477f9f';
  let playbackRate = 1, manualClock = false;
  function playback(value){running=value;elapsed=0;lastFrame=performance.now();}
  function snapshot(){return JSON.parse(JSON.stringify({source,signals,mode,order,quality,seed,mission,events,index,logOdds,player,revealed,comparison,reasonIndex,alternateHint}));}
  function remember(){previous=snapshot();}
  function syncControls(){$('mission').value=mission;$('mode').value=mode;$('order').value=order;$('quality').value=Math.round(quality*100);$('seed').value=seed;$('mission-brief').textContent=presets[mission].brief;}
  function begin(){signals=E.orderSignals(source.signals,order,seed);events=[];index=0;logOdds=0;player=null;revealed=false;running=false;elapsed=0;comparison=null;reasonIndex=-1;alternateHint=false;decisionTimes=[];revealTime=-10000;$('message').textContent=presets[mission].brief;syncControls();update();}
  function resetMission(){mission=$('mission').value;const preset=presets[mission];mode=preset.mode;order=preset.order;quality=.7;source=mission==='free'?E.generate(seed,quality):JSON.parse(JSON.stringify(example));previous=null;begin();}
  function step(){if(index>=12){playback(false);update();return;}const event=E.automatic(logOdds,signals[index],quality,mode);events.push(event);decisionTimes.push(appearanceTime());logOdds=event.after;index++;if(index===12){playback(false);$('message').textContent='이제 내 차례입니다. 나만 본 힌트와 공개된 정보를 보고 A 또는 B 상자를 직접 고르세요.';if(innerWidth<550&&!document.fullscreenElement&&!stage.classList.contains('expanded'))document.querySelector('.my-choice').scrollIntoView({behavior:ambientEnabled()?'smooth':'instant',block:'center'});}else $('message').textContent=mode==='independent'?`${index}명이 서로의 선택을 보지 않고 골랐습니다. 내 선택 전까지 다른 사람의 선택은 가려집니다.`:`${index}번째 사람은 ${letter(event.action)}를 골랐습니다. ${mode==='hints'?`그 사람이 본 힌트는 ${letter(signals[index-1])}입니다.`:'그 사람이 본 힌트는 아직 비공개입니다.'}`;update();}
  function choose(action){if(index!==12||player!==null)return;player=action;playback(false);$('message').textContent=`나는 ${letter(action)}를 골랐습니다. 이제 숨은 힌트와 정답을 공개해 긴 줄이 어디에서 시작됐는지 확인하세요.`;update();}
  function reveal(){if(player===null)return;revealed=true;revealTime=appearanceTime();const correct=events.filter(e=>e.action===source.truth).length+(player===source.truth?1:0),cascades=events.filter(e=>e.ignoresSignal).length;
    $('message').textContent=`정답은 ${letter(source.truth)}. ${correct}/13명이 맞혔습니다. ${mode==='choices'&&cascades?`${cascades}명은 어느 힌트를 보더라도 같은 선택을 할 상태였습니다. 선택 수가 그만큼의 독립적인 증거는 아니었습니다.`:'같은 힌트에서 공개 방식이나 입장 순서를 바꾸고 결과를 비교해 보세요.'}`;update();}
  function update(){
    $('play').textContent=running?'일시정지':index>=12?(player===null?'내 선택 대기':'관찰 완료'):'자동 재생';$('play').setAttribute('aria-pressed',String(running));$('play').disabled=index>=12;$('step').disabled=index>=12;$('status-chip').textContent=revealed?'숨은 정보 공개':player!==null?'내 선택 완료':index===12?'이제 내 차례':`앞사람 관찰 · ${index}/12`;
    $('private-hint').textContent=letter(signals.at(-1));$('private-hint').style.color=color(signals.at(-1));$('private-help').textContent=`힌트는 ${Math.round(quality*100)}%의 확률로 정답을 가리킵니다.`;
    for(const [id,value]of [['choose-a',1],['choose-b',-1]]){$(id).disabled=index!==12||player!==null;$(id).setAttribute('aria-pressed',String(player===value));}
    $('reveal').disabled=player===null||revealed;$('reveal').textContent=revealed?`정답 ${letter(source.truth)} · 힌트 공개됨`:'숨은 힌트·정답 공개';$('compare').disabled=!revealed;
    $('fs-next').hidden=index>=12;$('fs-next').textContent=running?'일시정지':'자동 재생';$('fs-reveal').hidden=player===null||revealed;
    $('step-stat').textContent=`${index} / 12`;$('belief-stat').textContent=mode==='independent'?'공개 안함':`${(E.logistic(logOdds)*100).toFixed(1)}%`;
    $('correct-stat').textContent=revealed?`${events.filter(e=>e.action===source.truth).length+(player===source.truth?1:0)} / 13`:'공개 전';$('quality-value').textContent=`${Math.round(quality*100)}%`;$('case-chip').textContent=mission==='free'?`시드 ${seed}`:'고른 사례';$('restore').disabled=!previous;
    $('comparison-note').textContent=comparison?'비교 막대는 13명 모두가 자동 판단한 결과입니다. 내 직접 선택은 위의 결과에만 포함됩니다. 정답·힌트·순서는 세 방식 모두 같습니다.':'먼저 직접 선택하고 숨은 힌트를 공개하세요. 그 뒤 같은 순서·같은 힌트의 세 방식을 비교할 수 있습니다.';updateReason();draw();
  }
  function reasoning(){if(!revealed||reasonIndex<0||!events[reasonIndex])return null;const event=events[reasonIndex],signal=signals[reasonIndex],opposite=-signal;return{position:reasonIndex+1,before:E.logistic(event.before),signal:letter(signal),posterior:event.posterior,choice:letter(event.action),after:E.logistic(event.after),ignoresSignal:event.ignoresSignal,oppositeSignal:letter(opposite),oppositePosterior:E.logistic(event.before+opposite*E.logit(quality)),oppositeChoice:letter(E.choose(event.before,opposite,quality))};}
  function updateReason(){
    $('reason-panel').hidden=!revealed;const r=reasoning();$('reason-person').value=reasonIndex<0?'':String(reasonIndex);$('reason-detail').hidden=!r;$('reason-intro').hidden=!!r;$('reason-heading').textContent=r?`${String(r.position).padStart(2,'0')}번째 사람의 판단`:'한 사람의 판단을 펼쳐 보세요';
    if(!r)return;const pct=p=>`${(p*100).toFixed(1)}%`;$('reason-before').textContent=pct(r.before);$('reason-signal').textContent=r.signal;$('reason-posterior').textContent=pct(r.posterior);$('reason-choice').textContent=r.choice;
    $('reason-explanation').textContent=mode==='independent'?'다른 선택을 보지 않아 A와 B를 50%씩에서 시작합니다. 자기 힌트만 반영해 고른 결과이며, 선택 전에는 서로에게 공개하지 않습니다.':r.ignoresSignal?`이 사람의 선택 뒤에도 공개 정보의 A 가능성은 ${pct(r.after)}로 그대로입니다. A 힌트를 보든 B 힌트를 보든 ${r.choice}를 고르므로, 반복된 선택이 새로운 증거를 더하지 않습니다.`:`이 사람이 받은 힌트를 합쳐 가능성이 큰 쪽을 골랐습니다. 정확히 같을 때는 자기 힌트를 따릅니다. 선택 뒤 공개 정보의 A 가능성은 ${pct(r.after)}입니다.`;
    $('alternate-hint').setAttribute('aria-pressed',String(alternateHint));$('alternate-result').hidden=!alternateHint;$('alternate-result').textContent=`힌트가 ${r.oppositeSignal}였다면 A 가능성은 ${pct(r.oppositePosterior)}, 선택은 ${r.oppositeChoice}입니다. ${r.oppositeChoice===r.choice?'힌트가 반대여도 선택은 같습니다.':'이번에는 선택이 달라집니다.'} 실제 실험 결과는 바꾸지 않습니다.`;
  }
  function selectPerson(value){if(!revealed)return;reasonIndex=value;alternateHint=false;update();}
  function resize(){const mobile=stage.clientWidth<550;W=mobile?360:900;H=mobile?600:560;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.aspectRatio=`${W}/${H}`;ctx.setTransform(dpr,0,0,dpr,0,0);draw();}
  function text(t,x,y,size=14,fill='#192d29',align='left',weight=500){ctx.font=`${weight} ${size}px system-ui,sans-serif`;ctx.fillStyle=fill;ctx.textAlign=align;ctx.textBaseline='middle';ctx.fillText(t,x,y);}
  function box(x,y,w,h,fill,stroke=null){ctx.beginPath();ctx.roundRect(x,y,w,h,9);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.lineWidth=1.5;ctx.strokeStyle=stroke;ctx.stroke();}}
  function cardGeometry(i){const mobile=W<550,pad=mobile?16:28,cols=mobile?4:6,gap=mobile?8:12,width=(W-pad*2-gap*(cols-1))/cols,height=mobile?65:76;return{x:pad+(i%cols)*(width+gap),y:(mobile?157:179)+Math.floor(i/cols)*(height+gap),width,height};}
  function curvePoint(a,b,c,d,t){const u=1-t;return{x:u*u*u*a.x+3*u*u*t*b.x+3*u*t*t*c.x+t*t*t*d.x,y:u*u*u*a.y+3*u*u*t*b.y+3*u*t*t*c.y+t*t*t*d.y};}
  function ribbons(time,mobile){
    if(mode==='independent'&&!revealed)return;const doorW=mobile?145:300,doorGap=mobile?18:52,doorX=(W-doorW*2-doorGap)/2;
    events.forEach((event,i)=>{const card=cardGeometry(i),start={x:card.x+card.width/2,y:card.y},end={x:doorX+(event.action===1?0:doorW+doorGap)+doorW/2,y:mobile?122:135},c1={x:start.x,y:start.y-(start.y-end.y)*.5},c2={x:end.x+(start.x-end.x)*.16,y:end.y+30};ctx.save();ctx.beginPath();ctx.moveTo(start.x,start.y);ctx.bezierCurveTo(c1.x,c1.y,c2.x,c2.y,end.x,end.y);ctx.strokeStyle=color(event.action);ctx.globalAlpha=reasonIndex===i?.35:.1;ctx.lineWidth=reasonIndex===i?4:2.4;ctx.stroke();
      if(ambientEnabled()){const t=(time/5600+i*.117)%1,head=curvePoint(start,c1,c2,end,t),tail=curvePoint(start,c1,c2,end,Math.max(0,t-.1)),gradient=ctx.createLinearGradient(tail.x,tail.y,head.x+.001,head.y+.001);gradient.addColorStop(0,color(event.action)+'00');gradient.addColorStop(1,color(event.action)+'cc');ctx.globalAlpha=.65;ctx.beginPath();for(let n=0;n<=7;n++){const p=curvePoint(start,c1,c2,end,Math.max(0,t-.1*(1-n/7)));if(n===0)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y);}ctx.strokeStyle=gradient;ctx.lineWidth=2.4;ctx.stroke();ctx.fillStyle=color(event.action);ctx.beginPath();ctx.arc(head.x,head.y,mobile?1.7:2.2,0,Math.PI*2);ctx.fill();}ctx.restore();
    });
  }
  function draw(){
    if(!signals)return;const mobile=W<550,pad=mobile?16:28,hideChoices=mode==='independent'&&!revealed,time=appearanceTime();
    ctx.clearRect(0,0,W,H);ctx.fillStyle='#f5f6f1';ctx.fillRect(0,0,W,H);
    ribbons(time,mobile);
    text(revealed?`정답 ${letter(source.truth)} · 힌트는 같아도 흐름은 달라집니다`:'당첨공은 A·B 상자 중 하나에 있습니다',pad,26,mobile?13:17,'#192d29','left',650);
    const counts=[events.filter(e=>e.action===1).length+(player===1?1:0),events.filter(e=>e.action===-1).length+(player===-1?1:0)],doorW=mobile?145:300,doorGap=mobile?18:52,doorX=(W-doorW*2-doorGap)/2;
    for(let i=0;i<2;i++){const v=i===0?1:-1,x=doorX+i*(doorW+doorGap);box(x,53,doorW,mobile?69:82,'#fff',revealed&&source.truth===v?'#b9763c':null);box(x+12,65,mobile?39:53,mobile?43:55,v===1?'#e7f0e5':'#e6eef2');text(letter(v),x+(mobile?31:38),mobile?88:94,mobile?27:34,color(v),'center',750);text(hideChoices?'선택 비공개':`${counts[i]}명 선택`,x+(mobile?95:170),mobile?88:94,mobile?14:22,color(v),'center',650);}
    const cols=mobile?4:6,gap=mobile?8:12,cardW=(W-pad*2-gap*(cols-1))/cols,cardH=mobile?65:76,top=mobile?157:179;
    text('입장 순서 →',pad,mobile?142:158,mobile?11:13,'#62706a');
    for(let i=0;i<12;i++){const x=pad+(i%cols)*(cardW+gap),y=top+Math.floor(i/cols)*(cardH+gap),e=events[i],shown=e&&(!hideChoices||revealed),hint=revealed||mode==='hints'&&i<index,isNext=i===index&&index<12,chosen=revealed&&reasonIndex===i;box(x,y,cardW,cardH,isNext||chosen?'#e7f0e5':'#fff',isNext||chosen?'#6f9e83':null);
      if(ambientEnabled()){const age=revealed?time-revealTime-i*24:time-(decisionTimes[i]??-10000);if(age>=0&&age<700&&(e||revealed)){ctx.save();ctx.globalAlpha=(1-age/700)*.28;box(x+2,y+2,cardW-4,cardH-4,'#a6cdb7');ctx.restore();}}
      text(String(i+1).padStart(2,'0'),x+8,y+12,mobile?9:10,'#87948b');text(shown?letter(e.action):e?'✓':'·',x+cardW/2,y+29,mobile?23:26,shown?color(e.action):'#b9c3b6','center',750);text(hint?`힌트 ${letter(signals[i])}`:'힌트 ?',x+cardW/2,y+cardH-13,mobile?10:11,hint?color(signals[i]):'#8b978d','center');if(revealed&&e.ignoresSignal){ctx.fillStyle='#bf824b';ctx.beginPath();ctx.arc(x+cardW-10,y+12,3,0,Math.PI*2);ctx.fill();}}
    const playerY=mobile?387:372,playerW=mobile?W-pad*2:420,playerX=(W-playerW)/2;box(playerX,playerY,playerW,60,index===12?'#e7f0e5':'#fff',index===12?'#6f9e83':null);text('13 · 나의 차례',playerX+14,playerY+19,12,'#62706a');text(`내 힌트 ${letter(signals.at(-1))}`,playerX+14,playerY+42,15,color(signals.at(-1)),'left',650);text(player===null?(index===12?'아래에서 선택 ↓':'앞사람을 관찰하세요'): `내 선택 ${letter(player)}`,playerX+playerW-14,playerY+31,mobile?14:17,player===null?'#62706a':color(player),'right',650);
    const footer=mobile?477:461;
    const reason=reasoning();
    if(reason){text(`${String(reason.position).padStart(2,'0')}번째: 판단 전 A ${(reason.before*100).toFixed(1)}%`,pad,footer,mobile?12:15,'#21654f');text(`내 힌트 ${reason.signal} → A ${(reason.posterior*100).toFixed(1)}% → ${reason.choice} 선택`,pad,footer+27,mobile?12:15,'#192d29');text(reason.ignoresSignal?'반대 힌트여도 같은 선택. 새 증거는 더해지지 않습니다.':'사람마다 당시 알고 있던 정보가 달랐습니다.',pad,footer+54,mobile?10:13,'#62706a');}
    else if(comparison){text('같은 힌트 · 자동 판단 13명 중 정답',pad,footer-12,mobile?11:12,'#62706a');comparison.forEach((r,i)=>{const y=footer+13+i*29,barX=mobile?107:185,barW=W-barX-pad-60;text(modeNames[r.mode],pad,y,mobile?11:13,'#62706a');box(barX,y-5,barW,10,'#e2e8dd');if(r.correct)box(barX,y-5,barW*r.correct/13,10,'#5d9675');text(`${r.correct}/13`,W-pad,y,mobile?12:14,'#21654f','right',650);});}
    else if(revealed){text('주황 점: 힌트가 반대여도 같은 선택',pad,footer,mobile?11:13,'#9e6c36');text('사람 카드를 눌러 판단의 흐름을 펼쳐 보세요.',pad,footer+29,mobile?12:15,'#21654f');}
    else{text(mode==='independent'?'각자 고르는 동안 다른 선택은 가립니다.':'선택이 같아도, 본 힌트까지 같은 것은 아닙니다.',pad,footer,mobile?11:14,'#62706a');text('내 선택 뒤에 숨은 힌트와 정답을 공개합니다.',pad,footer+27,mobile?11:14,'#62706a');}
  }
  function advance(ms){if(running){elapsed+=Math.max(0,ms)*playbackRate;while(elapsed+1e-7>=500&&running){elapsed-=500;step();}}if(ambientEnabled()||running)draw();}
  function restore(){if(!previous)return;const back=previous;previous=snapshot();({source,signals,mode,order,quality,seed,mission,events,index,logOdds,player,revealed,comparison,reasonIndex,alternateHint}=back);running=false;elapsed=0;decisionTimes=[];revealTime=-10000;syncControls();$('message').textContent='이전 실험의 힌트, 순서와 진행 상태를 복원했습니다.';update();}
  async function fullscreen(){if(document.fullscreenElement){await document.exitFullscreen();return;}if(stage.classList.contains('expanded')){stage.classList.remove('expanded');$('exit-fullscreen').hidden=true;$('fullscreen-controls').hidden=true;resize();return;}try{await stage.requestFullscreen();}catch{stage.classList.add('expanded');}$('exit-fullscreen').hidden=false;$('fullscreen-controls').hidden=false;resize();}
  $('play').onclick=()=>{if(index<12){playback(!running);update();}};$('step').onclick=()=>{playback(false);step();};$('reset').onclick=begin;$('mission').onchange=resetMission;$('choose-a').onclick=()=>choose(1);$('choose-b').onclick=()=>choose(-1);$('reveal').onclick=reveal;$('restore').onclick=restore;
  $('playback-speed').onchange=()=>{playbackRate=Number($('playback-speed').value);playback(running);update();};
  $('mode').onchange=()=>{remember();mode=$('mode').value;begin();};$('order').onchange=()=>{remember();order=$('order').value;begin();};
  $('quality').oninput=()=>{$('quality-value').textContent=`${$('quality').value}%`;};$('quality').onchange=()=>{remember();quality=Number($('quality').value)/100;mission='free';source=E.generate(seed,quality);begin();};
  $('seed').onchange=()=>{remember();seed=Math.min(999999,Math.max(1,Math.round(Number($('seed').value)||1)));mission='free';source=E.generate(seed,quality);begin();};
  $('new-seed').onclick=()=>{remember();seed=seed%999999+1;mission='free';source=E.generate(seed,quality);begin();};
  $('compare').onclick=()=>{if(!revealed)return;reasonIndex=-1;alternateHint=false;comparison=E.compare(signals,quality,source.truth);$('message').textContent='같은 정답, 같은 힌트, 같은 입장 순서입니다. 모든 사람이 모형의 규칙으로 판단할 때, 정보 공개 방식만 바꾼 결과를 비교합니다.';update();};
  for(let i=0;i<12;i++){const option=document.createElement('option');option.value=String(i);option.textContent=`${String(i+1).padStart(2,'0')}번째`; $('reason-person').append(option);}
  $('reason-person').onchange=()=>selectPerson($('reason-person').value===''?-1:Number($('reason-person').value));$('alternate-hint').onclick=()=>{alternateHint=!alternateHint;updateReason();draw();};
  function tapCanvas(event){const rect=canvas.getBoundingClientRect(),x=(event.clientX-rect.left)*W/rect.width,y=(event.clientY-rect.top)*H/rect.height;if(revealed){for(let i=0;i<12;i++){const card=cardGeometry(i);if(x>=card.x&&x<=card.x+card.width&&y>=card.y&&y<=card.y+card.height){selectPerson(i);return;}}}if(index!==12||player!==null)return;const mobile=W<550,doorW=mobile?145:300,gap=mobile?18:52,start=(W-doorW*2-gap)/2;if(y>=53&&y<=53+(mobile?69:82)){if(x>=start&&x<=start+doorW)choose(1);else if(x>=start+doorW+gap&&x<=start+doorW*2+gap)choose(-1);}}
  canvas.addEventListener('pointerdown',event=>{if(event.isPrimary&&event.button===0)pointerStart={id:event.pointerId,x:event.clientX,y:event.clientY,moved:false};});canvas.addEventListener('pointermove',event=>{if(pointerStart&&Math.hypot(event.clientX-pointerStart.x,event.clientY-pointerStart.y)>10)pointerStart.moved=true;});canvas.addEventListener('pointercancel',()=>{pointerStart=null;});canvas.addEventListener('pointerup',event=>{const start=pointerStart;pointerStart=null;if(!start||start.id!==event.pointerId||start.moved||Math.hypot(event.clientX-start.x,event.clientY-start.y)>10)return;tapCanvas(event);});
  window.addEventListener('websim:ambient-change',draw);
  $('fullscreen').onclick=fullscreen;$('exit-fullscreen').onclick=fullscreen;$('fs-next').onclick=()=>$('play').click();$('fs-reveal').onclick=reveal;document.addEventListener('fullscreenchange',()=>{const closed=!document.fullscreenElement&&!stage.classList.contains('expanded');$('exit-fullscreen').hidden=closed;$('fullscreen-controls').hidden=closed;resize();});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&stage.classList.contains('expanded')){fullscreen();return;}if(/INPUT|SELECT|TEXTAREA/.test(event.target.tagName))return;const key=event.key.toLowerCase();if(key==='f'){event.preventDefault();fullscreen();}else if(key==='a')choose(1);else if(key==='b')choose(-1);else if(event.key==='ArrowRight'){event.preventDefault();$('step').click();}else if(event.code==='Space'&&event.target.tagName!=='BUTTON'){event.preventDefault();$('play').click();}});
  window.render_game_to_text=()=>JSON.stringify({coordinates:'origin top-left, x right, y down',mission,mode,order,seed,quality,index,running,playbackRate,stepIntervalMs:500/playbackRate,playerSignal:letter(signals.at(-1)),playerChoice:player===null?null:letter(player),revealed,truth:revealed?letter(source.truth):null,publicProbabilityA:mode==='independent'?null:E.logistic(logOdds),people:events.map((e,i)=>({position:i+1,choice:mode==='independent'&&!revealed?null:letter(e.action),signal:revealed||mode==='hints'?letter(signals[i]):null,ignoresSignal:revealed?e.ignoresSignal:null})),comparison,effectsEnabled:ambientEnabled(),reason:reasoning(),alternateHint:revealed&&alternateHint,message:$('message').textContent});
  window.advanceTime=ms=>{manualClock=true;advance(Number(ms)||0);};new ResizeObserver(resize).observe(stage);resetMission();resize();requestAnimationFrame(function frame(t){const dt=lastFrame?Math.min(100,t-lastFrame):0;lastFrame=t;if(!manualClock)advance(dt);requestAnimationFrame(frame);});
})();
