const test=require('node:test'),assert=require('node:assert/strict'),E=require('./microbe-engine.js');
test('heterogeneous groups produce a real weighted Simpson reversal with lower within-group proportions',()=>{const s=E.create('paradox');for(let i=0;i<4;i++)E.step(s);const t=E.summary(s);assert.equal(t.paradox,true);assert.ok(t.dishes.every(d=>d.ratio<d.startRatio));assert.ok(t.ratio>t.startRatio);assert.ok(Math.abs(t.ratio-t.dishes.reduce((v,d)=>v+d.ratio*d.weight,0))<1e-12);assert.notEqual(t.ratio,t.meanRatio);});
test('uniform composition and rapidly saturating benefits provide non-reversal controls',()=>{for(const p of['uniform','saturated']){const s=E.create(p);for(let i=0;i<4;i++)E.step(s);assert.equal(E.summary(s).paradox,false,p);assert.ok(E.summary(s).ratio<.5,p);}});
test('production costs affect actual births and cannot exceed carrying capacities',()=>{const a=E.create('uniform'),b=E.create('uniform',73,{cost:0});E.step(a);E.step(b);assert.ok(a.dishes[0].p<b.dishes[0].p);assert.equal(a.dishes[0].n,b.dishes[0].n);for(let i=0;i<40;i++)E.step(a);for(const d of a.dishes){assert.ok(d.p+d.n<=d.capacity);assert.ok(Number.isInteger(d.p)&&Number.isInteger(d.n));}});
test('pipetting, splitting, mixing and merging conserve both types independently',()=>{const s=E.create();for(let i=0;i<3;i++)E.step(s);const before=E.totals(s),cap=s.dishes.reduce((v,d)=>v+d.capacity,0);E.transfer(s,1,2,101);assert.deepEqual(E.totals(s),before);assert.equal(E.transfer(s,1,1,10),false);E.split(s,2);assert.deepEqual(E.totals(s),before);assert.equal(s.dishes.reduce((v,d)=>v+d.capacity,0),cap);E.mix(s);assert.deepEqual(E.totals(s),before);E.merge(s);assert.deepEqual(E.totals(s),before);assert.equal(s.dishes.length,1);assert.equal(s.epochStep,0);});
test('seeded repeated interventions and growth replay exactly',()=>{const run=()=>{const s=E.create('paradox',42);E.transfer(s,4,1,33);E.split(s,3);for(let i=0;i<5;i++)E.step(s);return s;};assert.deepEqual(run(),run());});
test('transfers respect available receiving capacity and mixing conserves capacity',()=>{const s=E.create();s.dishes[1].capacity=203;const before=E.totals(s),capacity=s.dishes.reduce((v,d)=>v+d.capacity,0),moved=E.transfer(s,1,2,50);assert.equal(moved.p+moved.n,3);assert.deepEqual(E.totals(s),before);assert.equal(E.transfer(s,1,2,10),false);assert.equal(E.transfer(s,1,3,NaN),false);E.split(s,2);E.mix(s);assert.equal(s.dishes.reduce((v,d)=>v+d.capacity,0),capacity);assert.deepEqual(E.totals(s),before);assert.ok(s.dishes.every(d=>d.capacity>=d.p+d.n));});

const loadApp=require('../reef_market/app-test-harness.cjs');
test('culture playback shows sequential fixed generations, stops at thirty and reopens after splitting',()=>{const run=rate=>{const app=loadApp('microbial_commons','MicrobeEngine');app.select('playback-speed',String(rate));app.click('run');app.context.advanceTime(800*5/rate);return app;};const a=run(.5),b=run(4);assert.equal(a.state().step,5);assert.deepEqual(a.state().dishes,b.state().dishes);a.click('run');a.context.advanceTime(8000);assert.equal(a.state().step,5);a.click('run');a.click('step');assert.equal(a.state().step,6);assert.equal(a.state().running,false);a.click('run');a.context.advanceTime(800*100/.5);assert.equal(a.state().step,30);assert.equal(a.state().running,false);assert.equal(a.element('run').disabled,true);assert.equal(a.element('playback-progress').value,30);a.click('split');assert.equal(a.state().step,0);assert.equal(a.element('run').disabled,false);a.click('run');a.click('mix');assert.equal(a.state().running,false);});
