(()=>{'use strict';const E=window.MicrobeEngine,$=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d');let origin='paradox',s=E.create(),selected=1,running=false,last=null,elapsed=0,manual=false,pin=null,view={};const fmt=n=>Math.round(n).toLocaleString('ko-KR'),pct=x=>(x*100).toFixed(1)+'%',message=t=>$('message').textContent=t;
function stop(){running=false;elapsed=0;}
function selectors(){for(const id of['source','destination']){const old=$(id).value;$(id).replaceChildren(...s.dishes.map(d=>{const o=document.createElement('option');o.value=d.id;o.textContent=`${d.id}번 접시 · ${fmt(E.count(d))}개체`;return o;}));$(id).value=s.dishes.some(d=>d.id===Number(old))?old:String(s.dishes[0].id);}if(!s.dishes.some(d=>d.id===selected))selected=s.dishes[0].id;$('source').value=selected;if($('destination').value===String(selected)&&s.dishes.length>1)$('destination').value=s.dishes.find(d=>d.id!==selected).id;}
function card(x,y,w,h,stroke){ctx.fillStyle='#fff';ctx.strokeStyle=stroke;ctx.lineWidth=1.5;ctx.beginPath();ctx.roundRect(x,y,w,h,12);ctx.fill();ctx.stroke();}
function render(){const t=E.summary(s),mobile=window.innerWidth<=620,W=mobile?Math.max(240,$('stage').clientWidth-2):880,cols=mobile?2:s.dishes.length<=4?s.dishes.length:3,rows=Math.ceil(s.dishes.length/cols),cardH=mobile?187:221,H=80+rows*cardH+172,dpr=Math.min(2,window.devicePixelRatio||1);if(canvas.width!==Math.round(W*dpr)||canvas.height!==Math.round(H*dpr)){canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);view={W,H,cards:[]};ctx.fillStyle='#f5f6f1';ctx.fillRect(0,0,W,H);ctx.textAlign='left';ctx.font=mobile?'600 14px sans-serif':'600 19px sans-serif';ctx.fillStyle='#21654f';ctx.fillText(`전체 생산균 ${pct(t.ratio)}`,16,27);ctx.font='12px sans-serif';ctx.fillStyle='#718077';ctx.fillText(`● 초록 생산균  ● 산호 비생산균`,16,49);ctx.fillStyle='#21654f';ctx.fillRect(16,60,(W-32)*t.ratio,6);ctx.fillStyle='#c98474';ctx.fillRect(16+(W-32)*t.ratio,60,(W-32)*(1-t.ratio),6);
const gap=10,cw=(W-24-gap*(cols-1))/cols;
t.dishes.forEach((d,i)=>{const x=12+(i%cols)*(cw+gap),y=80+Math.floor(i/cols)*cardH,h=cardH-10;view.cards.push({id:d.id,x,y,w:cw,h});card(x,y,cw,h,d.id===selected?'#21654f':'#d4dfce');ctx.textAlign='center';ctx.fillStyle='#293d35';ctx.font='600 13px sans-serif';ctx.fillText(`${d.id}번 · ${pct(d.ratio)}`,x+cw/2,y+22);ctx.font='12px sans-serif';ctx.fillStyle='#718077';ctx.fillText(`시작 ${pct(d.startRatio)}`,x+cw/2,y+40);const r=mobile?Math.min(40,cw*.34):Math.min(52,cw*.32),cx=x+cw/2,cy=y+(mobile?89:105);ctx.fillStyle='#eef4e8';ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#b8cab0';ctx.lineWidth=2;ctx.stroke();const dots=58;for(let j=0;j<dots;j++){const a=j*2.399963+ d.id*.5,rr=Math.sqrt((j+.5)/dots)*r*.86;ctx.fillStyle=j<Math.round(dots*d.ratio)?'#39745a':'#c98474';ctx.beginPath();ctx.arc(cx+Math.cos(a)*rr,cy+Math.sin(a)*rr,mobile?2.0:2.8,0,Math.PI*2);ctx.fill();}ctx.font='600 12px sans-serif';ctx.fillStyle='#293d35';ctx.fillText(`${fmt(d.total)}개체`,cx,y+h-39);ctx.font='12px sans-serif';ctx.fillStyle='#718077';ctx.fillText(`전체의 ${pct(d.weight)}`,cx,y+h-21);ctx.fillStyle='#e6ece0';ctx.fillRect(x+9,y+h-12,cw-18,5);ctx.fillStyle='#467d60';ctx.fillRect(x+9,y+h-12,(cw-18)*d.weight,5);});
const chartY=80+rows*cardH+12;ctx.textAlign='left';ctx.font='12px sans-serif';ctx.fillStyle='#21654f';ctx.fillText('전체 비율',16,chartY);ctx.fillStyle='#7b8b75';ctx.fillText('접시 단순평균',mobile?96:125,chartY);ctx.fillStyle='#d5dfce';for(const p of[0,.5,1]){const y=chartY+21+90*(1-p);ctx.beginPath();ctx.moveTo(37,y);ctx.lineTo(W-17,y);ctx.strokeStyle='#dce4d6';ctx.stroke();ctx.fillStyle='#819078';ctx.font='10px sans-serif';ctx.fillText(Math.round(p*100)+'',9,y+3);}const points=s.history;for(const [field,color,dash]of[['ratio','#21654f',[]],['meanRatio','#879780',[4,4]]]){ctx.strokeStyle=color;ctx.lineWidth=2.5;ctx.setLineDash(dash);ctx.beginPath();points.forEach((p,i)=>{const x=37+i/Math.max(6,points.length-1)*(W-54),y=chartY+21+90*(1-p[field]);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();ctx.setLineDash([]);}ctx.fillStyle='#718077';ctx.font='12px sans-serif';ctx.textAlign='right';ctx.fillText(`현재 비교 구간 ${s.epochStep}세대`,W-16,H-12);
$('global-stat').textContent=pct(t.ratio);$('mean-stat').textContent=pct(t.meanRatio);$('population-stat').textContent=fmt(t.total);$('global-change').textContent=`기준보다 ${(100*(t.ratio-t.startRatio)).toFixed(1)}%p`;$('generation-stat').textContent=`전체 ${s.tick}세대 · 현재 구간 ${s.epochStep}세대`;$('run').textContent=running?'배양 멈춤':'자동 배양';$('mode-chip').textContent=t.paradox?'전체 방향 반전':running?'배양 중':s.epochStep?'결과 관찰':'배양 준비';$('cost').value=s.settings.cost;$('cost-value').textContent=s.settings.cost.toFixed(2);$('benefit').value=s.settings.benefit;$('benefit-value').textContent=s.settings.benefit.toFixed(1);$('response').value=s.settings.response;$('preset').value=s.preset;$('brief').textContent=E.PRESETS[s.preset].brief;
const d=t.dishes.find(d=>d.id===selected);$('dish-info').textContent=d?`${d.id}번: 생산균 ${fmt(d.p)} · 비생산균 ${fmt(d.n)}. 직전 배양 생산량 ${fmt(d.good)}. 새 생산균 +${fmt(d.birthP)}, 비생산균 +${fmt(d.birthN)}.`:'';$('transfer').disabled=s.dishes.length<2;$('split').disabled=s.dishes.length>=6||!d||d.total<2;$('mix').disabled=$('merge').disabled=s.dishes.length<2;
if(pin)$('comparison').textContent=`보관: 시드 ${pin.seed}, ${pin.step}세대, 전체 ${pct(pin.ratio)} / 단순평균 ${pct(pin.meanRatio)}. 비용 ${pin.settings.cost}, 효과 ${pin.settings.benefit}, ${pin.settings.response==='linear'?'비례':'포화'}, 시작 ${pin.origin==='uniform'?'같은 비율':'서로 다른 비율'}. 현재는 ${s.epochStep}세대입니다.${pin.seed!==s.seed?' 시드가 다릅니다.':''}`;}
function step(){if(s.epochStep>=30){stop();message('이 구간은 30세대까지입니다. 결과를 보관하거나 분주로 새 구간을 시작하세요.');render();return;}const t=E.step(s);selectors();message(t.paradox?'각 혼합 접시의 생산균 비율은 줄었지만, 전체 비율은 올라갔습니다. 더 커진 접시의 가중치를 보세요.':s.lastEvent);render();}
function reset(preset,keepSettings=false){stop();origin=preset;const wasFree=s.preset==='free',settings=keepSettings?{...s.settings}:{};s=E.create(origin,Number($('seed').value)||73,settings);if(keepSettings&&wasFree)s.preset='free';selected=1;selectors();message('같은 시드와 시작 접시를 준비했습니다. 배양 조건을 비교해 보세요.');render();}
$('step').onclick=()=>{stop();step();};$('run').onclick=()=>{running=!running;last=null;render();};$('reset').onclick=()=>reset(origin,true);$('preset').onchange=e=>reset(e.target.value);for(const k of['cost','benefit','response'])$(k).addEventListener(k==='response'?'change':'input',()=>{stop();E.change(s,k,$(k).value);message(s.lastEvent);render();});
$('source').onchange=e=>{selected=Number(e.target.value);render();};$('transfer').onclick=()=>{stop();const result=E.transfer(s,selected,Number($('destination').value),Number($('amount').value));message(result?s.lastEvent:'서로 다른 출발·도착 접시와 1개체 이상의 양을 골라 주세요.');selectors();render();};$('split').onclick=()=>{stop();E.split(s,selected);selectors();message(s.lastEvent);render();};$('merge').onclick=()=>{stop();E.merge(s);selected=1;selectors();message(s.lastEvent);render();};$('mix').onclick=()=>{stop();E.mix(s);selectors();message(s.lastEvent);render();};$('compare').onclick=()=>{pin={...E.summary(s),seed:s.seed,settings:{...s.settings},origin};message('현재 구간 결과를 보관했습니다. 조건을 바꾸고 같은 시드로 다시 출발해 보세요.');render();};
canvas.onpointerdown=e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*view.W/r.width,y=(e.clientY-r.top)*view.H/r.height;const hit=view.cards.find(c=>x>=c.x&&x<=c.x+c.w&&y>=c.y&&y<=c.y+c.h);if(hit){selected=hit.id;$('source').value=selected;render();}canvas.focus();};
async function fullscreen(){if($('stage').classList.contains('expanded'))$('stage').classList.remove('expanded');else if(document.fullscreenElement)await document.exitFullscreen();else try{if(!$('stage').requestFullscreen)throw Error();await $('stage').requestFullscreen();}catch{$('stage').classList.add('expanded');}render();}$('fullscreen').onclick=$('exit-fullscreen').onclick=fullscreen;document.addEventListener('fullscreenchange',render);document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('stage').classList.remove('expanded');render();}if(e.target.matches('input,select,textarea,button,a,[contenteditable]'))return;if(e.code==='Space'){e.preventDefault();running=!running;render();}if(e.key==='ArrowRight'){e.preventDefault();stop();step();}if(e.key.toLowerCase()==='f'){e.preventDefault();fullscreen();}});$('save').onclick=()=>{const a=document.createElement('a');a.download='websim-microbial-commons.png';a.href=canvas.toDataURL();a.click();};window.addEventListener('resize',render);
window.render_game_to_text=()=>JSON.stringify({coordinateSystem:'canvas top-left, x right, y down; dots show proportions, integer counts are model population',canvas:{width:view.W,height:view.H},preset:s.preset,seed:s.seed,settings:s.settings,running,selected,epoch:s.epoch,...E.summary(s),comparison:pin?{seed:pin.seed,step:pin.step,ratio:pin.ratio}:null});function advance(ms){if(!running)return;elapsed+=ms;while(elapsed>=800&&running){elapsed-=800;step();}}window.advanceTime=ms=>{manual=true;advance(ms);render();};function frame(t){if(!manual&&last!==null)advance(Math.min(100,t-last));last=t;requestAnimationFrame(frame);}selectors();render();document.fonts?.ready.then(render);requestAnimationFrame(frame);
})();
