(()=>{'use strict';const E=window.MicrobeEngine,$=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d');let origin='paradox',s=E.create(),selected=1,running=false,last=null,elapsed=0,manual=false,pin=null,view={},playbackRate=1;const fmt=n=>Math.round(n).toLocaleString('ko-KR'),pct=x=>(x*100).toFixed(1)+'%',message=t=>$('message').textContent=t;
const reduced=matchMedia('(prefers-reduced-motion: reduce)');let visualClock=0,lastVisualPaint=0,transition=null,pipette=false,pipetteFrom=null,pipetteTarget=null,press=null;
const effectsOn=()=>window.WebSimAmbient?.enabled===true&&!reduced.matches;
function beginTransition(before,kind='growth',fromId=null,toId=null,moved=null){transition=effectsOn()?{before,kind,fromId,toId,moved,start:visualClock,duration:Math.min(720,800/playbackRate*.85)}:null;}
function transitionProgress(){return transition&&effectsOn()?Math.min(1,(visualClock-transition.start)/transition.duration):1;}
function preview(){const from=s.dishes.find(d=>d.id===(pipetteFrom??selected)),to=s.dishes.find(d=>d.id===(pipetteTarget??Number($('destination').value)));if(!from||!to||from===to)return null;const amount=Math.max(0,Math.min(Math.round(Number($('amount').value)||0),E.count(from),to.capacity-E.count(to))),exact=amount*(E.count(from)?from.p/E.count(from):0);return{from:from.id,to:to.id,amount,pMin:Math.max(0,Math.min(amount,Math.floor(exact))),pMax:Math.max(0,Math.min(amount,Math.ceil(exact)))};}
function syncPipette(){const p=preview();$('pipette-mode').setAttribute('aria-pressed',String(pipette));$('pipette-mode').textContent=pipette?'스포이드 종료':'스포이드 모드';$('pipette-panel').hidden=!pipette;$('confirm-transfer').disabled=!pipetteFrom||!pipetteTarget||!p?.amount;$('transfer-preview').textContent=!pipetteFrom?'출발 접시를 한 번 누르세요. 다음에는 도착 접시를 누릅니다.':!pipetteTarget?`${pipetteFrom}번에서 가져옵니다. 다른 도착 접시를 누르세요.`:p?`${p.from}번 → ${p.to}번 · ${fmt(p.amount)}개체 이동 예정. 생산균 ${p.pMin===p.pMax?fmt(p.pMin):fmt(p.pMin)+'~'+fmt(p.pMax)}개체, 나머지는 비생산균입니다. 전체 개체수와 전체 비율은 보존됩니다.`:'접시를 다시 골라 주세요.';}
function pipetteReset(){pipetteFrom=null;pipetteTarget=null;syncPipette();}
function glass(cx,cy,r){ctx.save();ctx.shadowColor='#275a3920';ctx.shadowBlur=9;ctx.shadowOffsetY=4;const g=ctx.createRadialGradient(cx-r*.3,cy-r*.4,2,cx,cy,r);g.addColorStop(0,'#fcfffbd9');g.addColorStop(.78,'#e9f3e6c9');g.addColorStop(1,'#d5e5d7b3');ctx.fillStyle=g;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.shadowOffsetY=0;ctx.strokeStyle='#a8c2ae';ctx.lineWidth=1.5;ctx.stroke();ctx.beginPath();ctx.arc(cx,cy,r-3,0,Math.PI*2);ctx.strokeStyle='#ffffffdb';ctx.lineWidth=1.3;ctx.stroke();ctx.beginPath();ctx.arc(cx-1,cy-1,r-6,Math.PI*1.1,Math.PI*1.67);ctx.strokeStyle='#ffffffec';ctx.lineWidth=3;ctx.stroke();ctx.restore();}
function flow(){const active=transition&&transition.kind==='transfer'&&transitionProgress()<1?transition:null,fromId=active?active.fromId:pipetteFrom,toId=active?active.toId:pipetteTarget;if(!fromId||!toId)return;const a=view.cards.find(c=>c.id===fromId),b=view.cards.find(c=>c.id===toId);if(!a||!b)return;const ax=a.x+a.w/2,ay=a.cy,bx=b.x+b.w/2,by=b.cy,cx=(ax+bx)/2,cy=Math.min(ay,by)-35;ctx.save();ctx.strokeStyle='#447d6590';ctx.lineWidth=1.5;ctx.setLineDash([3,5]);ctx.beginPath();ctx.moveTo(ax,ay);ctx.quadraticCurveTo(cx,cy,bx,by);ctx.stroke();ctx.setLineDash([]);if(active){const p=transitionProgress();for(let i=0;i<5;i++){const q=Math.max(0,Math.min(1,p*1.4-i*.09)),x=(1-q)**2*ax+2*(1-q)*q*cx+q*q*bx,y=(1-q)**2*ay+2*(1-q)*q*cy+q*q*by;ctx.fillStyle=i<Math.round(5*active.moved.p/(active.moved.p+active.moved.n))?'#39745a':'#c98474';ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill();}}ctx.restore();}
function stop(){running=false;elapsed=0;}

function selectors(){for(const id of['source','destination']){const old=$(id).value;$(id).replaceChildren(...s.dishes.map(d=>{const o=document.createElement('option');o.value=d.id;o.textContent=`${d.id}번 접시 · ${fmt(E.count(d))}개체`;return o;}));$(id).value=s.dishes.some(d=>d.id===Number(old))?old:String(s.dishes[0].id);}if(!s.dishes.some(d=>d.id===selected))selected=s.dishes[0].id;$('source').value=selected;if($('destination').value===String(selected)&&s.dishes.length>1)$('destination').value=s.dishes.find(d=>d.id!==selected).id;}
function card(x,y,w,h,stroke){ctx.fillStyle='#fff';ctx.strokeStyle=stroke;ctx.lineWidth=1.5;ctx.beginPath();ctx.roundRect(x,y,w,h,12);ctx.fill();ctx.stroke();}
function render(updateUI=true){const t=E.summary(s),mobile=window.innerWidth<=620,W=Math.min(880,Math.max(240,Math.round($('stage').clientWidth-2))),cols=mobile?2:s.dishes.length<=4?s.dishes.length:3,rows=Math.ceil(s.dishes.length/cols),cardH=mobile?187:221,H=80+rows*cardH+172,dpr=Math.min(2,window.devicePixelRatio||1);if(canvas.width!==Math.round(W*dpr)||canvas.height!==Math.round(H*dpr)){canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);view={W,H,cards:[]};ctx.fillStyle='#f5f6f1';ctx.fillRect(0,0,W,H);ctx.textAlign='left';ctx.font=mobile?'600 14px sans-serif':'600 19px sans-serif';ctx.fillStyle='#21654f';ctx.fillText(`전체 생산균 ${pct(t.ratio)}`,16,27);ctx.font='12px sans-serif';ctx.fillStyle='#718077';ctx.fillText(`● 초록 생산균  ● 산호 비생산균`,16,49);ctx.fillStyle='#21654f';ctx.fillRect(16,60,(W-32)*t.ratio,6);ctx.fillStyle='#c98474';ctx.fillRect(16+(W-32)*t.ratio,60,(W-32)*(1-t.ratio),6);
const gap=10,cw=(W-24-gap*(cols-1))/cols;
t.dishes.forEach((d,i)=>{const x=12+(i%cols)*(cw+gap),y=80+Math.floor(i/cols)*cardH,h=cardH-10;view.cards.push({id:d.id,x,y,w:cw,h,cy:y+(mobile?89:105)});card(x,y,cw,h,d.id===pipetteTarget?'#b48c57':d.id===selected?'#21654f':'#d4dfce');ctx.textAlign='center';ctx.fillStyle='#293d35';ctx.font='600 13px sans-serif';ctx.fillText(`${d.id}번 · ${pct(d.ratio)}`,x+cw/2,y+22);ctx.font='12px sans-serif';ctx.fillStyle='#718077';ctx.fillText(`시작 ${pct(d.startRatio)}`,x+cw/2,y+40);const r=mobile?Math.min(40,cw*.34):Math.min(52,cw*.32),cx=x+cw/2,cy=y+(mobile?89:105);glass(cx,cy,r);const dots=58,old=transition?.before.dishes.find(q=>q.id===d.id),phase=transitionProgress(),ease=phase*phase*(3-2*phase);for(let j=0;j<dots;j++){const a=j*2.399963+d.id*.5,rr=Math.sqrt((j+.5)/dots)*r*.82,dx=effectsOn()?Math.sin(visualClock*.00065+j*3.1+d.id)*1.05:0,dy=effectsOn()?Math.cos(visualClock*.00057+j*2.3)*1.05:0;const was=j<Math.round(dots*(old?old.ratio:d.ratio)),now=j<Math.round(dots*d.ratio);const fill=now?'#39745a':'#c98474';ctx.fillStyle=was!==now&&phase<1?(was?'#39745a':'#c98474'):fill;ctx.beginPath();ctx.ellipse(cx+Math.cos(a)*rr+dx,cy+Math.sin(a)*rr+dy,mobile?2.2:3,mobile?1.7:2.2,a,0,Math.PI*2);ctx.fill();if(was!==now&&phase<1){ctx.globalAlpha=ease;ctx.fillStyle=fill;ctx.fill();ctx.globalAlpha=1;}}if(old&&transition.kind==='growth'&&phase<1){ctx.beginPath();ctx.arc(cx,cy,r+2+phase*5,0,Math.PI*2);ctx.strokeStyle=`rgba(73,133,91,${.5*(1-phase)})`;ctx.lineWidth=2;ctx.stroke();}ctx.font='600 12px sans-serif';ctx.fillStyle='#293d35';ctx.fillText(`${fmt(d.total)}개체`,cx,y+h-39);ctx.font='12px sans-serif';ctx.fillStyle='#718077';ctx.fillText(`전체의 ${pct(d.weight)}`,cx,y+h-21);ctx.fillStyle='#e6ece0';ctx.fillRect(x+9,y+h-12,cw-18,5);ctx.fillStyle='#467d60';ctx.fillRect(x+9,y+h-12,(cw-18)*d.weight,5);});
flow();const chartY=80+rows*cardH+12;ctx.textAlign='left';ctx.font='12px sans-serif';ctx.fillStyle='#21654f';ctx.fillText('전체 비율',16,chartY);ctx.fillStyle='#7b8b75';ctx.fillText('접시 단순평균',mobile?96:125,chartY);ctx.fillStyle='#d5dfce';for(const p of[0,.5,1]){const y=chartY+21+90*(1-p);ctx.beginPath();ctx.moveTo(37,y);ctx.lineTo(W-17,y);ctx.strokeStyle='#dce4d6';ctx.stroke();ctx.fillStyle='#819078';ctx.font='12px sans-serif';ctx.fillText(Math.round(p*100)+'',9,y+3);}const points=s.history;for(const [field,color,dash]of[['ratio','#21654f',[]],['meanRatio','#879780',[4,4]]]){ctx.strokeStyle=color;ctx.lineWidth=2.5;ctx.setLineDash(dash);ctx.beginPath();points.forEach((p,i)=>{const x=37+i/Math.max(6,points.length-1)*(W-54),y=chartY+21+90*(1-p[field]);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();ctx.setLineDash([]);}ctx.fillStyle='#718077';ctx.font='12px sans-serif';ctx.textAlign='right';ctx.fillText(`현재 비교 구간 ${s.epochStep}세대`,W-16,H-12);
if(updateUI){$('global-stat').textContent=pct(t.ratio);$('mean-stat').textContent=pct(t.meanRatio);$('population-stat').textContent=fmt(t.total);$('global-change').textContent=`기준보다 ${(100*(t.ratio-t.startRatio)).toFixed(1)}%p`;$('generation-stat').textContent=`전체 ${s.tick}세대 · 현재 구간 ${s.epochStep}세대`;$('run').textContent=running?'Ⅱ 일시정지':'▶ 연속 배양';$('run').setAttribute('aria-pressed',String(running));$('run').disabled=s.epochStep>=30;$('step').disabled=s.epochStep>=30;$('playback-progress').value=s.epochStep;$('playback-state').textContent=`${s.epochStep} / 30세대 · ${s.epochStep>=30?'배양 완료':running?'연속 재생 중':'멈춤'} · ${playbackRate}×`;$('mode-chip').textContent=t.paradox?'전체 방향 반전':running?'배양 중':s.epochStep?'결과 관찰':'배양 준비';$('cost').value=s.settings.cost;$('cost-value').textContent=s.settings.cost.toFixed(2);$('benefit').value=s.settings.benefit;$('benefit-value').textContent=s.settings.benefit.toFixed(1);$('response').value=s.settings.response;$('preset').value=s.preset;$('brief').textContent=E.PRESETS[s.preset].brief;
const d=t.dishes.find(d=>d.id===selected);$('dish-info').textContent=d?`${d.id}번: 생산균 ${fmt(d.p)} · 비생산균 ${fmt(d.n)}. 직전 배양 생산량 ${fmt(d.good)}. 새 생산균 +${fmt(d.birthP)}, 비생산균 +${fmt(d.birthN)}.`:'';$('transfer').disabled=s.dishes.length<2;$('split').disabled=s.dishes.length>=6||!d||d.total<2;$('mix').disabled=$('merge').disabled=s.dishes.length<2;
syncPipette();if(pin)$('comparison').textContent=`보관: 시드 ${pin.seed}, ${pin.step}세대, 전체 ${pct(pin.ratio)} / 단순평균 ${pct(pin.meanRatio)}. 비용 ${pin.settings.cost}, 효과 ${pin.settings.benefit}, ${pin.settings.response==='linear'?'비례':'포화'}, 시작 ${pin.origin==='uniform'?'같은 비율':'서로 다른 비율'}. 현재는 ${s.epochStep}세대입니다.${pin.seed!==s.seed?' 시드가 다릅니다.':''}`;}}
function step(){if(s.epochStep>=30){stop();message('이 구간은 30세대까지입니다. 결과를 보관하거나 분주로 새 구간을 시작하세요.');render();return;}const before=E.summary(s),t=E.step(s);if(s.epochStep>=30)stop();beginTransition(before);selectors();message(s.epochStep>=30?'30세대 배양을 마쳐 멈췄습니다. 결과를 보관하거나 분주로 새 구간을 시작하세요.':t.paradox?'각 혼합 접시의 생산균 비율은 줄었지만, 전체 비율은 올라갔습니다. 더 커진 접시의 가중치를 보세요.':s.lastEvent);render();}
function reset(preset,keepSettings=false){stop();transition=null;pipetteFrom=null;pipetteTarget=null;origin=preset;const wasFree=s.preset==='free',settings=keepSettings?{...s.settings}:{};s=E.create(origin,Number($('seed').value)||73,settings);if(keepSettings&&wasFree)s.preset='free';selected=1;selectors();message('같은 시드와 시작 접시를 준비했습니다. 배양 조건을 비교해 보세요.');render();}
$('step').onclick=()=>{stop();step();};function togglePlayback(){if(running)stop();else if(s.epochStep<30){running=true;elapsed=0;last=null;pipette=false;pipetteReset();}render();}$('run').onclick=togglePlayback;$('playback-speed').onchange=()=>{playbackRate=Number($('playback-speed').value)||1;elapsed=0;last=null;render();};$('reset').onclick=()=>reset(origin,true);$('preset').onchange=e=>reset(e.target.value);for(const k of['cost','benefit','response'])$(k).addEventListener(k==='response'?'change':'input',()=>{stop();E.change(s,k,$(k).value);message(s.lastEvent);render();});
$('source').onchange=e=>{selected=Number(e.target.value);if(pipette){pipetteFrom=selected;pipetteTarget=null;}render();};
function doTransfer(){stop();const from=pipette&&pipetteFrom?pipetteFrom:selected,to=pipette&&pipetteTarget?pipetteTarget:Number($('destination').value),before=E.summary(s),result=E.transfer(s,from,to,Number($('amount').value));if(result)beginTransition(before,'transfer',from,to,result);message(result?s.lastEvent:'서로 다른 접시와 도착 접시의 남은 수용량을 확인해 주세요.');selectors();render();}
$('transfer').onclick=$('confirm-transfer').onclick=doTransfer;$('pipette-mode').onclick=()=>{stop();pipette=!pipette;pipetteReset();render();};$('amount').oninput=()=>{$('pipette-amount').value=$('amount').value;syncPipette();};$('pipette-amount').oninput=()=>{$('amount').value=$('pipette-amount').value;syncPipette();};$('destination').onchange=()=>{if(pipette){pipetteFrom=selected;pipetteTarget=Number($('destination').value);}render();};$('split').onclick=()=>{stop();pipetteReset();transition=null;E.split(s,selected);selectors();message(s.lastEvent);render();};$('merge').onclick=()=>{stop();pipetteReset();transition=null;E.merge(s);selected=1;selectors();message(s.lastEvent);render();};$('mix').onclick=()=>{stop();pipetteReset();transition=null;E.mix(s);selectors();message(s.lastEvent);render();};$('compare').onclick=()=>{pin={...E.summary(s),seed:s.seed,settings:{...s.settings},origin};message('현재 구간 결과를 보관했습니다. 조건을 바꾸고 같은 시드로 다시 출발해 보세요.');render();};
canvas.addEventListener('pointerdown',e=>{press={id:e.pointerId,x:e.clientX,y:e.clientY,moved:false};});canvas.addEventListener('pointermove',e=>{if(press&&press.id===e.pointerId&&Math.hypot(e.clientX-press.x,e.clientY-press.y)>9)press.moved=true;});canvas.addEventListener('pointercancel',()=>press=null);canvas.addEventListener('pointerup',e=>{if(!press||press.id!==e.pointerId||press.moved||Math.hypot(e.clientX-press.x,e.clientY-press.y)>9){press=null;return;}press=null;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*view.W/r.width,y=(e.clientY-r.top)*view.H/r.height,hit=view.cards.find(c=>x>=c.x&&x<=c.x+c.w&&y>=c.y&&y<=c.y+c.h);if(hit){if(pipette){if(pipetteFrom===null){pipetteFrom=hit.id;selected=hit.id;$('source').value=hit.id;}else if(hit.id!==pipetteFrom){pipetteTarget=hit.id;$('destination').value=hit.id;}}else{selected=hit.id;$('source').value=selected;}render();}canvas.focus({preventScroll:true});});

async function fullscreen(){if($('stage').classList.contains('expanded'))$('stage').classList.remove('expanded');else if(document.fullscreenElement)await document.exitFullscreen();else try{if(!$('stage').requestFullscreen)throw Error();await $('stage').requestFullscreen();}catch{$('stage').classList.add('expanded');}render();}$('fullscreen').onclick=$('exit-fullscreen').onclick=fullscreen;document.addEventListener('fullscreenchange',render);document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('stage').classList.remove('expanded');render();}if(e.target.matches('input,select,textarea,button,a,[contenteditable]'))return;if(e.code==='Space'){e.preventDefault();togglePlayback();}if(e.key==='ArrowRight'){e.preventDefault();stop();step();}if(e.key.toLowerCase()==='f'){e.preventDefault();fullscreen();}});$('save').onclick=()=>{const a=document.createElement('a');a.download='websim-microbial-commons.png';a.href=canvas.toDataURL();a.click();};window.addEventListener('resize',render);
window.render_game_to_text=()=>JSON.stringify({coordinateSystem:'canvas top-left, x right, y down; dots show proportions, integer counts are model population',canvas:{width:view.W,height:view.H},preset:s.preset,seed:s.seed,settings:s.settings,running,playbackRate,selected,pipette:{enabled:pipette,from:pipetteFrom,to:pipetteTarget,preview:preview()},effects:effectsOn(),epoch:s.epoch,...E.summary(s),comparison:pin?{seed:pin.seed,step:pin.step,ratio:pin.ratio}:null});function advance(ms){if(!running)return;elapsed+=ms*playbackRate;while(elapsed+1e-7>=800&&running){elapsed-=800;step();}}window.advanceTime=ms=>{manual=true;if(effectsOn())visualClock+=Math.max(0,Number(ms)||0);advance(ms);render();};function frame(t){if(!manual&&last!==null){const dt=Math.min(100,t-last);advance(dt);if(effectsOn()){visualClock+=dt;if(visualClock-lastVisualPaint>=33){render(false);lastVisualPaint=visualClock;}}}last=t;requestAnimationFrame(frame);}window.addEventListener('websim:ambient-change',()=>{if(!effectsOn())transition=null;render();});reduced.addEventListener('change',()=>{if(!effectsOn())transition=null;render();});selectors();render();document.fonts?.ready.then(render);requestAnimationFrame(frame);
})();
