// Browser checks for decorative motion and the two observation aids; no model changes.
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{createRequire}=require('node:module');
let pw;try{pw=require('playwright');}catch{pw=createRequire(path.join(process.env.USERPROFILE||process.env.HOME,'.codex/skills/develop-web-game/package.json'))('playwright');}
const output=path.resolve(__dirname,'../output/playwright/ambient-review/routes-cascade'),base=process.env.WEBSIM_URL||'http://127.0.0.1:4173/';
const get=page=>page.evaluate(()=>JSON.parse(window.render_game_to_text()));
const sameModel=(a,b)=>{delete a.effectsEnabled;delete b.effectsEnabled;assert.deepEqual(a,b);};
(async()=>{
  await fs.mkdir(output,{recursive:true});const browser=await pw.chromium.launch({headless:true,...(process.platform==='win32'?{executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}:{})});const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  for(const lab of ['braess_city','information_cascade']){
    await page.goto(base+lab+'/'+lab+'.html');await page.waitForFunction(()=>window.render_game_to_text&&window.WebSimAmbient);await page.evaluate(()=>window.WebSimAmbient.setEnabled(true));
    if(lab==='braess_city'){await page.click('#toggle-road');assert.equal((await get(page)).average,65);assert.match(await page.locator('#edge-changes').innerText(),/4,000 → 2,000대/);}
    else{assert.equal(await page.locator('#reason-panel').isVisible(),false);await page.click('#play');await page.evaluate(()=>window.advanceTime(6000));assert.equal((await get(page)).reason,null);assert.ok((await get(page)).people.every(p=>p.signal===null));await page.click('#choose-b');await page.click('#reveal');await page.selectOption('#reason-person','2');let s=await get(page);assert.equal(s.reason.position,3);assert.ok(Math.abs(s.reason.before-.49/.58)<1e-8);assert.ok(Math.abs(s.reason.posterior-.7)<1e-8);assert.equal(s.reason.choice,'A');await page.click('#alternate-hint');assert.equal((await get(page)).alternateHint,true);assert.match(await page.locator('#alternate-result').innerText(),/선택은 A/);await page.selectOption('#reason-person','0');assert.equal((await get(page)).reason.oppositeChoice,'B');await page.selectOption('#reason-person','2');}
    await page.waitForTimeout(150);const before=await get(page);await page.evaluate(()=>window.WebSimAmbient.setEnabled(false));const off=await get(page);assert.equal(off.effectsEnabled,false);sameModel(before,off);const pixels=await page.locator('canvas').evaluate(c=>c.toDataURL());await page.waitForTimeout(250);assert.equal(await page.locator('canvas').evaluate(c=>c.toDataURL()),pixels);await page.evaluate(()=>window.WebSimAmbient.setEnabled(true));
    for(const width of [1440,390,360]){await page.setViewportSize({width,height:1000});await page.waitForTimeout(120);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(output,`${lab}-${width}.png`),fullPage:true});await page.locator('canvas').screenshot({path:path.join(output,`${lab}-canvas-${width}.png`)});}
    await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>!window.WebSimAmbient.enabled);assert.equal((await get(page)).effectsEnabled,false);const still=await page.locator('canvas').evaluate(c=>c.toDataURL());await page.waitForTimeout(120);assert.equal(await page.locator('canvas').evaluate(c=>c.toDataURL()),still);await page.emulateMedia({reducedMotion:'no-preference'});await page.waitForFunction(()=>window.WebSimAmbient.enabled);
    if(lab==='information_cascade'){await page.selectOption('#mode','independent');await page.click('#play');await page.evaluate(()=>window.advanceTime(6000));assert.ok((await get(page)).people.every(p=>p.choice===null&&p.signal===null));await page.click('#choose-b');await page.click('#reveal');await page.selectOption('#reason-person','2');assert.equal((await get(page)).reason.before,.5);assert.equal((await get(page)).reason.choice,'B');}
  }
  const touch=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),tp=await touch.newPage(),cdp=await touch.newCDPSession(tp);
  for(const lab of ['braess_city','information_cascade']){
    await tp.goto(base+lab+'/'+lab+'.html');await tp.waitForFunction(()=>window.render_game_to_text);
    if(lab==='information_cascade'){await tp.locator('#play').tap();await tp.evaluate(()=>window.advanceTime(6000));await tp.locator('#choose-b').tap();await tp.locator('#reveal').tap();}
    await tp.locator('canvas').scrollIntoViewIfNeeded();let b=await tp.locator('canvas').boundingBox();const x=b.x+b.width*(lab==='braess_city'?.5:.61),y=b.y+b.height*(lab==='braess_city'?225/480:185/600),before=await get(tp),scrollBefore=await tp.evaluate(()=>scrollY);
    await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:y-90}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await tp.waitForTimeout(160);sameModel(before,await get(tp));assert.notEqual(await tp.evaluate(()=>scrollY),scrollBefore);
    await tp.locator('canvas').scrollIntoViewIfNeeded();b=await tp.locator('canvas').boundingBox();await tp.touchscreen.tap(b.x+b.width*(lab==='braess_city'?.5:.61),b.y+b.height*(lab==='braess_city'?225/480:185/600));if(lab==='braess_city')assert.equal((await get(tp)).config.open,false);else assert.equal((await get(tp)).reason.position,3);
  }
  const missing=await browser.newContext();await missing.route('**/assets/ambient.js',route=>route.fulfill({contentType:'application/javascript',body:''}));const mp=await missing.newPage();for(const lab of ['braess_city','information_cascade']){await mp.goto(base+lab+'/'+lab+'.html');await mp.waitForFunction(()=>window.render_game_to_text);assert.equal((await get(mp)).effectsEnabled,false);}
  assert.deepEqual(errors,[]);await fs.writeFile(path.join(output,'result.json'),JSON.stringify({passed:true,errors,checks:['motion does not mutate model','effect-off canvas is still','OS reduced motion','missing API fallback','1440/390/360 screenshots','public-only ribbons','person reasoning and counterfactual','touch scroll does not trigger tap','touch taps still work']},null,2));await browser.close();console.log('Ambient and observation checks passed:',output);
})().catch(e=>{console.error(e);process.exit(1);});
