// Optional browser regression check. Run with a localhost static server already serving WebSim.
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { createRequire } = require('node:module');
let playwright; try { playwright = require('playwright'); } catch { playwright = createRequire(path.join(process.env.USERPROFILE || process.env.HOME, '.codex/skills/develop-web-game/package.json'))('playwright'); }
const base = process.env.WEBSIM_URL || 'http://127.0.0.1:4173/';
const output = path.resolve(__dirname, '../output/playwright/social-ecology/routes-cascade');
const state = page => page.evaluate(() => JSON.parse(window.render_game_to_text()));
const near = (a,b) => assert.ok(Math.abs(a-b)<.025, `${a} != ${b}`);
(async()=>{
  await fs.mkdir(output,{recursive:true});
  await fs.writeFile(path.join(output,'actions.json'),JSON.stringify({steps:[{buttons:[],frames:360}]}));
  const browser=await playwright.chromium.launch({headless:true,...(process.platform==='win32'?{executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}:{})});
  const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  await page.goto(base+'braess_city/braess_city.html');await page.waitForFunction(()=>window.render_game_to_text);near((await state(page)).average,80);
  await page.click('#toggle-road');near((await state(page)).average,65);assert.ok((await state(page)).completed.includes('paradox'));
  await page.click('#restore');near((await state(page)).average,80);
  await page.selectOption('#mission','quiet');await page.click('#toggle-road');await page.evaluate(()=>window.advanceTime(4000));let s=await state(page);near(s.average,20);assert.equal(s.running,false);assert.ok(s.completed.includes('quiet'));assert.equal(s.flows[0],0);
  await page.selectOption('#mission','busy');const old=(await state(page)).average;await page.click('#toggle-road');near((await state(page)).average,old);assert.ok((await state(page)).completed.includes('busy'));
  await page.selectOption('#mission','paradox');await page.click('[data-route="2"]');assert.equal((await state(page)).selectedRoute,2);await page.click('#toggle-road');await page.click('#compare');near((await state(page)).previous.average,80);await page.screenshot({path:path.join(output,'braess-desktop.png'),fullPage:true});
  await page.click('#fullscreen');await page.waitForTimeout(50);assert.equal(await page.locator('#exit-fullscreen').isVisible(),true);await page.click('#exit-fullscreen');
  await page.evaluate(()=>{document.getElementById('stage').requestFullscreen=()=>Promise.reject(new Error('fallback check'));});await page.click('#fullscreen');assert.equal(await page.locator('#stage').evaluate(e=>e.classList.contains('expanded')),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#exit-fullscreen').isVisible(),false);
  for(const width of [820,390,360]){await page.setViewportSize({width,height:920});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('canvas').count(),1);assert.equal(await page.locator('h1').count(),1);await page.screenshot({path:path.join(output,`braess-${width}.png`),fullPage:true});}
  await page.setViewportSize({width:1440,height:1050});await page.goto(base+'information_cascade/information_cascade.html');await page.waitForFunction(()=>window.render_game_to_text);assert.equal((await state(page)).truth,null);
  await page.click('#step');await page.click('#step');near((await state(page)).publicProbabilityA, .49/.58);await page.click('#play');await page.evaluate(()=>window.advanceTime(6000));s=await state(page);assert.equal(s.index,12);assert.equal(s.running,false);assert.ok(s.people.every(p=>p.signal===null));near(s.publicProbabilityA,.49/.58);
  await page.click('#choose-b');assert.equal((await state(page)).revealed,false);await page.click('#reveal');s=await state(page);assert.equal(s.truth,'B');assert.equal(s.people.filter(p=>p.ignoresSignal).length,10);await page.click('#compare');s=await state(page);assert.equal(s.comparison.find(x=>x.mode==='choices').correct,0);
  await page.screenshot({path:path.join(output,'cascade-desktop.png'),fullPage:true});
  await page.selectOption('#mode','hints');await page.click('#play');await page.evaluate(()=>window.advanceTime(6000));assert.ok((await state(page)).people.every(p=>p.signal!==null));await page.click('#restore');s=await state(page);assert.equal(s.mode,'choices');assert.equal(s.revealed,true);assert.equal(s.playerChoice,'B');
  await page.selectOption('#order','reverse');await page.click('#play');await page.evaluate(()=>window.advanceTime(6000));s=await state(page);assert.ok(s.people.every(p=>p.choice==='B'));assert.equal(s.playerSignal,'B');
  await page.selectOption('#mode','independent');await page.click('#play');await page.evaluate(()=>window.advanceTime(6000));s=await state(page);assert.ok(s.people.every(p=>p.choice===null));assert.equal(s.publicProbabilityA,null);await page.click('#choose-b');await page.click('#reveal');assert.ok((await state(page)).people.every(p=>p.choice!==null));
  await page.click('#new-seed');const seeded=await state(page);await page.click('#play');await page.evaluate(()=>window.advanceTime(6000));await page.click('#choose-a');await page.click('#reveal');const known=await state(page);await page.click('#reset');await page.click('#play');await page.evaluate(()=>window.advanceTime(6000));await page.click('#choose-a');await page.click('#reveal');assert.equal((await state(page)).truth,known.truth);assert.equal((await state(page)).playerSignal,seeded.playerSignal);
  await page.selectOption('#mission','cascade');await page.click('#play');await page.evaluate(()=>window.advanceTime(6000));await page.click('#choose-b');await page.click('#reveal');await page.click('#compare');
  for(const width of [820,390,360]){await page.setViewportSize({width,height:920});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('canvas').count(),1);assert.equal(await page.locator('h1').count(),1);await page.screenshot({path:path.join(output,`cascade-${width}.png`),fullPage:true});}
  await page.click('#fullscreen');await page.waitForTimeout(50);assert.equal(await page.locator('#exit-fullscreen').isVisible(),true);await page.click('#exit-fullscreen');
  const touch=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const tp=await touch.newPage();
  await tp.goto(base+'braess_city/braess_city.html');await tp.waitForFunction(()=>window.render_game_to_text);await tp.locator('#canvas').scrollIntoViewIfNeeded();const bounds=await tp.locator('#canvas').boundingBox();await tp.touchscreen.tap(bounds.x+bounds.width*.5,bounds.y+bounds.height*(215/480));near((await state(tp)).average,65);
  await tp.goto(base+'information_cascade/information_cascade.html');await tp.locator('#play').tap();await tp.evaluate(()=>window.advanceTime(6000));await tp.locator('#choose-b').tap();await tp.locator('#reveal').tap();assert.equal((await state(tp)).revealed,true);
  await tp.locator('#reset').tap();await tp.locator('#fullscreen').tap();await tp.locator('#fs-next').tap();await tp.evaluate(()=>window.advanceTime(6000));const cb=await tp.locator('#canvas').boundingBox();await tp.touchscreen.tap(cb.x+cb.width*.73,cb.y+cb.height*(88/600));assert.equal((await state(tp)).playerChoice,'B');await tp.locator('#fs-reveal').tap();assert.equal((await state(tp)).revealed,true);await tp.locator('#exit-fullscreen').tap();
  const nojs=await browser.newContext({javaScriptEnabled:false});const dp=await nojs.newPage();for(const name of ['braess_city','information_cascade']){await dp.goto(base+`${name}/${name}_doc.html`);assert.equal(await dp.locator('h1').count(),1);await dp.locator('details summary').click();assert.ok((await dp.locator('article').innerText()).length>2000);}
  assert.deepEqual(errors,[]);await fs.writeFile(path.join(output,'result.json'),JSON.stringify({passed:true,errors,checks:['engagement flows','counterfactual comparison','restore','deterministic signals','fullscreen and fallback','360/390/820/1440 layouts','actual touch','docs without JavaScript']},null,2));await browser.close();console.log('Browser checks passed:',output);
})().catch(error=>{console.error(error);process.exit(1);});
