(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ReefEngine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
  function random(seed,tick,channel,id,index=0){let h=(seed^Math.imul(tick+1,2654435761)^Math.imul(channel+1,2246822519)^Math.imul(id+1,3266489917)^Math.imul(index+1,668265263))>>>0;h=Math.imul(h^(h>>>16),2246822507)>>>0;h=Math.imul(h^(h>>>13),3266489909)>>>0;return((h^(h>>>16))>>>0)+.5;}
  const u=(...args)=>random(...args)/4294967296;
  const PRESETS={
    audience:{name:'01 · 소문이 선택으로 이어질 때',choice:'all',memory:.9,observation:.75,temptation:1.7,brief:'손님은 본 일을 기억하고 가게를 고릅니다. 30라운드 정도 운영하며 청소율과 실제 방문 수를 함께 읽어 보세요.'},
    captive:{name:'02 · 볼 수 있지만 떠날 수 없다면',choice:'none',memory:.9,observation:.75,temptation:1.7,brief:'관찰은 같지만 손님에게 다른 가게를 고를 권한이 없습니다. 관찰만으로 결과가 정해지는지 비교하세요.'},
    forget:{name:'03 · 보아도 선택에 쓰지 않는다면',choice:'all',memory:0,observation:.75,temptation:1.7,brief:'모든 가게가 열려 있지만 지난 서비스의 기억을 선택에 쓰지 않습니다. 가게 수가 같아도 다른 결과가 나올 수 있습니다.'},
    free:{name:'자유 실험 · 통로와 평판',choice:'all',memory:.9,observation:.75,temptation:1.7,brief:'통로·영업 여부·관찰 범위를 바꿔 보세요. 물고기나 가게를 누르면 최근 선택과 보상의 이유를 볼 수 있습니다.'}
  };
  function create(preset='audience',seed=42,overrides={}){const p=PRESETS[preset]||PRESETS.audience;return{preset,seed:Number(seed)>>>0,tick:0,settings:{choice:p.choice,memory:p.memory,observation:p.observation,temptation:p.temptation,learning:.22,...overrides},gates:[true,true],shops:[0,1,2].map(i=>({id:i,x:.18+i*.32,y:.69,open:true,q:[4.0+.15*i,3.8-.1*i],pending:null,visits:0,action:'clean',lastReward:null,revenue:0,services:0,cleanServices:0})),clients:Array.from({length:18},(_,i)=>({id:i,home:i%3,visitor:i%2===0,x:.07+.86*u(seed,0,0,i),y:.18+.28*u(seed,0,1,i),fromX:0,fromY:0,target:i%3,parasites:3+Math.floor(u(seed,0,2,i)*4),memory:[.5,.5,.5],lastReason:'아직 방문하지 않았습니다.',lastService:'none',observed:[]})),history:[],lastEvents:[],totalServices:0,totalClean:0,lastEvent:'가게 세 곳과 손님 18마리를 준비했습니다.'};}
  function reachable(s,c){const open=s.shops.filter(p=>p.open);let home=s.shops[c.home].open?c.home:open.reduce((a,b)=>Math.abs(a.x-s.shops[c.home].x)<Math.abs(b.x-s.shops[c.home].x)?a:b).id;if(s.settings.choice==='none'||(s.settings.choice==='visitors'&&!c.visitor))return[home];const reached=new Set([home]),queue=[home];while(queue.length){const j=queue.shift();for(const next of[j-1,j+1])if(next>=0&&next<3&&s.gates[Math.min(j,next)]&&!reached.has(next)){reached.add(next);queue.push(next);}}return[...reached].filter(j=>s.shops[j].open);}
  function choose(s,c){const options=reachable(s,c),scores=options.map(id=>{const shop=s.shops[id],distance=Math.abs(shop.x-s.shops[c.home].x),quality=4*s.settings.memory*c.memory[id];const noise=-Math.log(-Math.log(u(s.seed,s.tick,3,c.id,id)))*.24;return{id,score:quality-.65*distance+noise,quality,distance,remembered:c.memory[id]};});scores.sort((a,b)=>b.score-a.score);const explore=u(s.seed,s.tick,7,c.id)<.08;const selected=explore?scores[Math.floor(u(s.seed,s.tick,8,c.id)*scores.length)]:scores[0];return{...selected,options,explore};}
  function step(s){
    const plans=s.clients.map(c=>choose(s,c)),visits=[0,0,0];plans.forEach(p=>visits[p.id]++);s.lastEvents=[];
    for(const shop of s.shops){shop.visits=visits[shop.id];if(shop.pending){const reward=shop.pending.food+3*(shop.visits/6);const a=shop.pending.action==='clean'?0:1;shop.q[a]+=s.settings.learning*(reward-shop.q[a]);shop.lastReward={food:shop.pending.food,nextVisitors:shop.visits,future:3*(shop.visits/6),total:reward,action:shop.pending.action};shop.pending=null;}if(!shop.open||!shop.visits){shop.action='idle';continue;}const probClean=1/(1+Math.exp(clamp((shop.q[1]-shop.q[0])/.35,-30,30)));shop.action=u(s.seed,s.tick,4,shop.id)<probClean?'clean':'mucus';shop.pending={action:shop.action,food:shop.action==='clean'?1:s.settings.temptation};shop.services+=shop.visits;shop.cleanServices+=shop.action==='clean'?shop.visits:0;shop.revenue+=shop.visits*shop.pending.food;}
    for(let i=0;i<s.clients.length;i++){const c=s.clients[i],plan=plans[i],shop=s.shops[plan.id];c.fromX=c.x;c.fromY=c.y;c.target=shop.id;c.x=clamp(shop.x+(u(s.seed,s.tick,5,c.id)-.5)*.22,.04,.96);c.y=.24+u(s.seed,s.tick,6,c.id)*.29;c.parasites=Math.min(8,c.parasites+1);if(shop.action==='clean')c.parasites=Math.max(0,c.parasites-2);c.lastService=shop.action;c.observed=[];const quality=shop.action==='clean'?1:0;c.memory[shop.id]+=.55*(quality-c.memory[shop.id]);const label=String.fromCharCode(65+shop.id);c.lastReason=plan.options.length===1?`${label}만 방문 가능: 이동 선택권 또는 통로 제한`:`${label} 선택${plan.explore?' (8% 재방문 탐색)':''}: 당시 기억 ${Math.round(plan.remembered*100)}% · 후보 ${plan.options.map(j=>String.fromCharCode(65+j)).join('/')} · 기억 가중치 ${s.settings.memory.toFixed(1)}, 거리도 반영`;}
    for(const c of s.clients){for(const shop of s.shops){if(shop.id===c.target||shop.action==='idle')continue;const distance=Math.hypot(c.x-shop.x,c.y-shop.y);if(s.settings.observation>0&&distance<=s.settings.observation){const q=shop.action==='clean'?1:0;c.memory[shop.id]+=.3*(q-c.memory[shop.id]);c.observed.push(shop.id);}}}
    const clean=s.shops.reduce((n,p)=>n+(p.action==='clean'?p.visits:0),0);s.totalServices+=s.clients.length;s.totalClean+=clean;s.tick++;const point={tick:s.tick,cleanRate:clean/s.clients.length,totalRate:s.totalClean/s.totalServices,visits:[...visits],parasites:s.clients.reduce((v,c)=>v+c.parasites,0)/s.clients.length};s.history.push(point);if(s.history.length>80)s.history.shift();s.lastEvents=s.shops.filter(p=>p.visits).map(p=>`${String.fromCharCode(65+p.id)} ${p.action==='clean'?'기생충 청소':'점액 먹기'} · ${p.visits}마리 방문`);s.lastEvent=s.lastEvents.join(' / ');return point;
  }
  function gate(s,index){if(index!==0&&index!==1)return false;s.gates[index]=!s.gates[index];s.preset='free';return true;}
  function setOpen(s,id,open){const shop=s.shops[id];if(!shop)return false;if(!open&&s.shops.filter(p=>p.open).length===1&&shop.open)return false;shop.open=Boolean(open);s.preset='free';return true;}
  function change(s,key,value){if(key==='choice')s.settings.choice=['all','visitors','none'].includes(value)?value:'all';if(key==='memory')s.settings.memory=clamp(Number(value),0,1);if(key==='observation')s.settings.observation=clamp(Number(value),0,1);if(key==='temptation')s.settings.temptation=clamp(Number(value),1,3);s.preset='free';}
  function summary(s){const last=s.history[s.history.length-1];return{tick:s.tick,totalRate:s.totalServices?s.totalClean/s.totalServices:null,cleanRate:last?last.cleanRate:null,parasites:s.clients.reduce((n,c)=>n+c.parasites,0)/s.clients.length,shops:s.shops.map(p=>({id:p.id,open:p.open,visits:p.visits,action:p.action,q:[...p.q],lastReward:p.lastReward,services:p.services,cleanServices:p.cleanServices})),gates:[...s.gates]};}
  return{PRESETS,create,step,reachable,choose,gate,setOpen,change,summary,random:u};
});
