const test=require('node:test'),assert=require('node:assert/strict'),E=require('./reef-engine.js');
const run=(preset,settings={},rounds=60)=>{const s=E.create(preset,42,settings);for(let i=0;i<rounds;i++)E.step(s);return s;};
test('identical seeds reproduce all individual decisions and learned values',()=>assert.deepEqual(run('audience'),run('audience')));
test('observers do not directly force service; no exit means observation cannot affect rewards',()=>{const a=E.create('captive',42,{observation:0}),b=E.create('captive',42,{observation:1});for(let t=0;t<50;t++){E.step(a);E.step(b);assert.deepEqual(a.shops,b.shops);}assert.notDeepEqual(a.clients.map(c=>c.memory),b.clients.map(c=>c.memory));});
test('observation changes memories before it can influence a subsequent visit',()=>{const a=E.create('audience',42,{observation:0}),b=E.create('audience',42,{observation:1});E.step(a);E.step(b);assert.deepEqual(a.shops,b.shops);assert.notDeepEqual(a.clients.map(c=>c.memory),b.clients.map(c=>c.memory));assert.ok(b.clients.some(c=>c.observed.length>0));});
test('future visitor reward is settled from actual next visits and actual preceding action',()=>{const s=E.create();E.step(s);const pending=s.shops.map(p=>p.pending&&{...p.pending});E.step(s);s.shops.forEach((p,i)=>{if(pending[i]){assert.equal(p.lastReward.action,pending[i].action);assert.equal(p.lastReward.food,pending[i].food);assert.equal(p.lastReward.nextVisitors,p.visits);assert.equal(p.lastReward.total,pending[i].food+p.visits*.5);}});});
test('closed corridors constrain choices and closing a busy shop reroutes clients without reset',()=>{const s=run('audience');const busiest=s.shops.slice().sort((a,b)=>b.visits-a.visits)[0];assert.ok(E.setOpen(s,busiest.id,false));E.step(s);assert.equal(s.shops[busiest.id].visits,0);assert.ok(s.clients.every(c=>c.target!==busiest.id));assert.equal(s.shops.reduce((n,p)=>n+p.visits,0),18);const c=E.create();E.gate(c,0);E.gate(c,1);for(const f of c.clients)assert.deepEqual(E.reachable(c,f),[f.home]);assert.ok(E.setOpen(c,0,false));assert.ok(E.setOpen(c,1,false));assert.equal(E.setOpen(c,2,false),false);});
test('cooperative service removes actual parasites, bounded counts survive long runs',()=>{const s=E.create();s.shops.forEach(p=>p.q=[100,-100]);const before=s.clients.map(c=>c.parasites);E.step(s);s.clients.forEach((c,i)=>assert.equal(c.parasites,before[i]-1));for(let i=0;i<100;i++)E.step(s);assert.ok(s.clients.every(c=>c.parasites>=0&&c.parasites<=8));});
test('the three guided experiments differ through incentives, not a preset outcome',()=>{const a=run('audience'),b=run('captive'),c=run('forget');assert.ok(E.summary(a).totalRate>E.summary(b).totalRate+.2);assert.ok(E.summary(a).totalRate>E.summary(c).totalRate+.2);assert.ok(a.shops.every(p=>p.services>0));const before=a.clients.map(f=>f.target);E.change(a,'memory',0);for(let i=0;i<10;i++)E.step(a);assert.notDeepEqual(a.clients.map(f=>f.target),before);assert.ok(a.shops.every(p=>p.visits>0));});
test('spatial routes use physical detours and coral occludes a sightline',()=>{const s=E.create();E.terrainPreset(s,'open');const a={x:.1,y:.5},b={x:.9,y:.5},open=E.route(s,a,b);s.terrain.cells[4*15+7]=1;const detour=E.route(s,a,b);assert.ok(detour.distance>open.distance);assert.equal(E.visible(s,a,b),false);assert.ok(detour.ids.every(i=>s.terrain.cells[i]===0));});
test('terrain preserves reachable services, rejects blocking a shop and replays seeded choices',()=>{const a=E.create(),b=E.create();assert.ok(E.terrainPreset(a,'central'));assert.ok(E.terrainPreset(b,'central'));assert.equal(E.paint(a,a.shops[0].x,a.shops[0].y,true),false);for(let i=0;i<12;i++){E.step(a);E.step(b);assert.equal(E.validTerrain(a),true);assert.ok(a.clients.every(c=>!a.terrain.cells[E.cell(a,c.x,c.y)]));}assert.deepEqual(a.shops,b.shops);assert.deepEqual(a.clients,b.clients);});
test('audience memory respects coral occlusion, not just observation radius',()=>{const s=E.create();E.terrainPreset(s,'open');s.terrain.cells[4*15+7]=1;assert.equal(E.visible(s,{x:.3,y:.5},{x:.7,y:.5}),false);s.settings.spatial=false;assert.equal(E.visible(s,{x:.3,y:.5},{x:.7,y:.5}),true);});

test('stale terrain snapshots cannot place clients inside restored coral after movement',()=>{for(const [preset,rounds]of[['central',2],['passages',3]]){const s=E.create('audience',42);E.terrainPreset(s,preset);const snapshot={cells:[...s.terrain.cells],spatial:true};E.terrainPreset(s,'open');for(let i=0;i<rounds;i++)E.step(s);const before=JSON.stringify(s.terrain);assert.equal(E.restoreTerrain(s,snapshot),false);assert.equal(JSON.stringify(s.terrain),before);assert.ok(E.validTerrain(s));assert.ok(E.step(s));}});
test('unreachable clients and an all-closed market stop a whole round without partial accounting',()=>{const old=E.create('audience',42);E.terrainPreset(old,'central');const s=E.create('audience',1,{spatial:true});s.terrain=structuredClone(old.terrain);assert.equal(E.validTerrain(s),false);const before=structuredClone(s);assert.equal(E.step(s),null);delete before.lastEvent;const after=structuredClone(s);delete after.lastEvent;assert.deepEqual(after,before);assert.match(s.lastEvent,/진행하지 않았/);const closed=E.create();closed.shops.forEach(p=>p.open=false);assert.deepEqual(E.reachable(closed,closed.clients[0]),[]);assert.equal(E.step(closed),null);assert.equal(closed.tick,0);});
const loadApp=require('./app-test-harness.cjs');
test('real UI expires terrain undo on progress and keeps safe immediate undo',()=>{for(const [preset,rounds]of[['central',2],['passages',3]]){const app=loadApp('reef_market','ReefEngine');app.select('terrain-preset',preset);const terrain=app.state().terrain;app.select('terrain-preset','open');assert.equal(app.element('terrain-undo').disabled,false);app.click('terrain-undo');assert.deepEqual(app.state().terrain,terrain);app.select('terrain-preset','open');for(let i=0;i<rounds;i++)app.click('step');assert.equal(app.element('terrain-undo').disabled,true);app.forceClick('terrain-undo');assert.ok(app.state().terrain.cells.every(v=>v===0));app.click('step');assert.equal(app.state().tick,rounds+1);assert.match(app.element('terrain-undo-hint').textContent,/戻|되돌릴 수 없/);}});
test('real UI rejects a new-seed reset when retained coral blocks its initial clients',()=>{const app=loadApp('reef_market','ReefEngine');app.select('terrain-preset','central');const before=app.state();app.element('seed').value='1';app.click('reset');assert.equal(app.state().seed,42);assert.equal(Number(app.element('seed').value),42);assert.deepEqual(app.state().terrain,before.terrain);assert.match(app.element('message').textContent,/초기화하지 않았/);app.click('step');assert.equal(app.state().tick,1);});
test('starting, keyboard running and access-condition changes invalidate reef undo immediately',()=>{for(const action of[app=>app.click('run'),app=>app.key(' ','Space'),app=>app.click('gate-0'),app=>app.select('choice','visitors')]){const app=loadApp('reef_market','ReefEngine');app.select('terrain-preset','central');action(app);assert.equal(app.element('terrain-undo').disabled,true);}});
