const test=require('node:test'),assert=require('node:assert/strict'),E=require('./reef-engine.js');
const run=(preset,settings={},rounds=60)=>{const s=E.create(preset,42,settings);for(let i=0;i<rounds;i++)E.step(s);return s;};
test('identical seeds reproduce all individual decisions and learned values',()=>assert.deepEqual(run('audience'),run('audience')));
test('observers do not directly force service; no exit means observation cannot affect rewards',()=>{const a=E.create('captive',42,{observation:0}),b=E.create('captive',42,{observation:1});for(let t=0;t<50;t++){E.step(a);E.step(b);assert.deepEqual(a.shops,b.shops);}assert.notDeepEqual(a.clients.map(c=>c.memory),b.clients.map(c=>c.memory));});
test('observation changes memories before it can influence a subsequent visit',()=>{const a=E.create('audience',42,{observation:0}),b=E.create('audience',42,{observation:1});E.step(a);E.step(b);assert.deepEqual(a.shops,b.shops);assert.notDeepEqual(a.clients.map(c=>c.memory),b.clients.map(c=>c.memory));assert.ok(b.clients.some(c=>c.observed.length>0));});
test('future visitor reward is settled from actual next visits and actual preceding action',()=>{const s=E.create();E.step(s);const pending=s.shops.map(p=>p.pending&&{...p.pending});E.step(s);s.shops.forEach((p,i)=>{if(pending[i]){assert.equal(p.lastReward.action,pending[i].action);assert.equal(p.lastReward.food,pending[i].food);assert.equal(p.lastReward.nextVisitors,p.visits);assert.equal(p.lastReward.total,pending[i].food+p.visits*.5);}});});
test('closed corridors constrain choices and closing a busy shop reroutes clients without reset',()=>{const s=run('audience');const busiest=s.shops.slice().sort((a,b)=>b.visits-a.visits)[0];assert.ok(E.setOpen(s,busiest.id,false));E.step(s);assert.equal(s.shops[busiest.id].visits,0);assert.ok(s.clients.every(c=>c.target!==busiest.id));assert.equal(s.shops.reduce((n,p)=>n+p.visits,0),18);const c=E.create();E.gate(c,0);E.gate(c,1);for(const f of c.clients)assert.deepEqual(E.reachable(c,f),[f.home]);assert.ok(E.setOpen(c,0,false));assert.ok(E.setOpen(c,1,false));assert.equal(E.setOpen(c,2,false),false);});
test('cooperative service removes actual parasites, bounded counts survive long runs',()=>{const s=E.create();s.shops.forEach(p=>p.q=[100,-100]);const before=s.clients.map(c=>c.parasites);E.step(s);s.clients.forEach((c,i)=>assert.equal(c.parasites,before[i]-1));for(let i=0;i<100;i++)E.step(s);assert.ok(s.clients.every(c=>c.parasites>=0&&c.parasites<=8));});
test('the three guided experiments differ through incentives, not a preset outcome',()=>{const a=run('audience'),b=run('captive'),c=run('forget');assert.ok(E.summary(a).totalRate>E.summary(b).totalRate+.2);assert.ok(E.summary(a).totalRate>E.summary(c).totalRate+.2);assert.ok(a.shops.every(p=>p.services>0));const before=a.clients.map(f=>f.target);E.change(a,'memory',0);for(let i=0;i<10;i++)E.step(a);assert.notDeepEqual(a.clients.map(f=>f.target),before);assert.ok(a.shops.every(p=>p.visits>0));});
